- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
Ken Olson caught this a year ago in his pull request #29, but
it was my oversight; when rearranging the sqlj relations back
in #10 to accommodate more than one deployment descriptor, I
updated the sql in install_jar and remove_jar (and deployInstall
and deployRemove), but I just totally overlooked replace_jar. Oops.
> Fix obsoleted query in sqlj.replace_jar.

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Triggers.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/UsingPropertiesAsScalarSet.java
A change from javac 6 to 7 in how javax.lang.model type objects are returned caused the DDR generator's automated type mapping to break. Others noticed the problem and added an explicit type to the annotated function where the problem was seen, which only served to mask the problem.
This adds a workaround in the DDR generator so it once again finds the right type, and reverts the change that added the explicit annotation.
Under this workaround, type mapping will only work right in a build where all of the sources with pljava annotations in them are present in round 1. That will be the normal case. Someone would have to be doing something very fancy with _other_ annotation processors generating new sources with pljava annotations in them during the build, in order to need annotations to be …
> Workaround #39 breakage seen with Java 7

- pljava/src/main/java/org/postgresql/pljava/internal/Backend.java
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
Previously determined the order of multiple deployment descriptors in
a single jar according to the order of those entries as stored in the jar
(used in that order for install, and that order reversed for remove).
But that wasn't correct. I got my hands on 2003 and 2006 drafts of the
SQL/JRT spec and they both clearly say it is the order _as the entries
are listed in the manifest_ that matters (again, in that order for install,
and the reverse for remove).
This should be a welcome improvement, because I had noted back in
commit 0edc9e5f that maven doesn't always put things in a jar in
the same order, and that was causing the pljava-examples jar to be
broken about half the time (for autodeployment anyway). But the manifest
is a static file listing the ddrs in the right order, so as long as …
> Run deployment descriptors in correct order.

- pljava-so/src/main/c/Function.c
Spun the loop in parseParameters slightly so it doesn't complain in the
corner case of an explicit method signature of no parameters. Also made
the messages clearer for when the signature really doesn't match what's
expected.
Will resolve #8, I dare to hope.
> Address #8 spurious error with zero-arg method sigs.

- .gitignore
- pljava-ant/src/main/java/org/postgresql/pljava/tasks/package-info.java
- pljava-api/src/main/java/org/postgresql/pljava/ObjectPool.java
- pljava-api/src/main/java/org/postgresql/pljava/ResultSetHandle.java
- pljava-api/src/main/java/org/postgresql/pljava/ResultSetProvider.java
- pljava-api/src/main/java/org/postgresql/pljava/SavepointListener.java
- pljava-api/src/main/java/org/postgresql/pljava/Session.java
- pljava-api/src/main/java/org/postgresql/pljava/TransactionListener.java
- pljava-api/src/main/java/org/postgresql/pljava/TriggerData.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/Function.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLActions.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLType.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/Trigger.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/package-info.java
- pljava-api/src/main/java/org/postgresql/pljava/package-info.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/TriggerNamer.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/package-info.java
- pljava-deploy/src/main/java/org/postgresql/pljava/deploy/package-info.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/package-info.java
- pljava/src/main/java/org/postgresql/pljava/internal/package-info.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/package-info.java
- pljava/src/main/java/org/postgresql/pljava/management/package-info.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/package-info.java
- pom.xml
Now `mvn clean package site site:stage` will produce a (very basic, uncustomized) directory tree representing a web site under `target/staging`. It includes generated javadocs for everything (and I've also spent a bit of time completing javadocs, at least the ones I noticed missing and felt competent to write).
In order to make maven do this, I had to put a site URL into `pom.xml` and you will see that I used `http://tada.github.io/pljava/` which is (I think) what the project's [GitHub Pages](https://help.github.com/articles/creating-project-pages-manually/) URL would be, if you were to enable that feature. So, you may detect in this pull request a faint, implicit suggestion about doing that. :)
I can see in the repository that there already is a `gh-pages` branch where you did some …
> Enable maven features to build a basic tech-detail site

- pljava-so/src/main/c/Backend.c
This was one problem being solved two ways. First there was code
to double any percent signs in a string that would be passed to elog.
But then myrkraverk in 2012 (622d0ac) got a compiler warning about
using a non-constant format string, and changed the elog call to
pass the supplied string as an argument to `%s` format, which is the
cleaner solution anyway, but didn't remove the old code, so `%` signs
were printing out doubled.
> The rest of "Bugfix 1011181"

- msvc-build-notes.txt
- pljava-so/build.xml
- pljava-so/pom.xml
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/JNICalls.c
- pljava-so/src/main/c/jvm.def
- pljava-so/src/main/c/type/Timestamp.c
Code changes to allow compilation and linking with Microsoft
Visual C. Maven build process conditionalized to to detect Visual C
and adjust options appropriately. See msvc-build-notes.txt for
full details.
> Fix to allow building pljava with Microsoft Visual C

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/package-info.java
I want to close issue #39 (pull #42 provided a workaround), but the
workaround has a limitation and in case anybody runs into it, it should
be mentioned in at least one place that doesn't have to be looked up
in closed issues or in the code.
> Note limitation of the workaround in pull #42.

- pljava-so/src/main/c/Exception.c
- pljava-so/src/main/c/JNICalls.c
- pljava-so/src/main/include/pljava/JNICalls.h
That way other exceptions (like a problem in a class initializer, or
out of memory) will not be hidden from view. Closes #54.
> Only ignore the expected exception in method lookup.

- pljava-so/pom.xml
- pljava-so/src/main/c/Exception.c
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/type/Array.c
- pljava-so/src/main/c/type/ErrorData.c
- pljava-so/src/main/c/type/Float.c
- pljava-so/src/main/c/type/Timestamp.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/c/type/UDT.c
- pljava-so/src/main/include/pljava/pljava.h
The `nar-maven-plugin` enables pretty much the whole artillery of `gcc` warnings. The `sign-conversion` ones just aren't practical because macros included from PostgreSQL headers produce floods of them. To deal with that I just created the `wnosign` profile in the POM to turn them off:
mvn -P wnosign compile
(which uses a `gcc`-specific option, so using `-P wnosign` with any other compiler will probably just fail). Then I could concentrate on the remaining diagnostics. Also added the property `nar.cores` which can be set to `1` if intermingled messages from _n_ compile threads are hard to follow:
mvn -Dnar.cores=1 -P wnosign compile
Then it's pretty much manageable, and a matter of tracking the warnings down. Some were just matters of convincing the compiler something was correct. Then …
> Cull gcc warnings to a comprehensible number.

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Function.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLAction.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/package-info.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRWriter.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/Lexicals.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ConditionalDDR.java
- pljava-examples/src/main/resources/deployment/examples.ddr
- pljava-so/src/main/c/Backend.c
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
- pljava/src/main/java/org/postgresql/pljava/management/DDRExecutor.java
- pljava/src/main/java/org/postgresql/pljava/management/SQLDeploymentDescriptor.java
This is the "installment 1" portion of conditional code execution within the deployment descriptor, as [proposed on pljava-dev][prop1]. It uses the deployment-descriptor feature of "implementor blocks" (code snippets wrapped in `BEGIN `_identifier_ and `END `_identifier_ and intended to execute only in contexts that recognize that _identifier_ for that purpose) and creates a new GUC variable `pljava.implementors` that can be adjusted (at query time by ordinary SQL code) listing the identifiers that will be recognized. So, SQL code in an always-executed block of the deployment descriptor can test arbitrary things, then set up which _other_ "implementor blocks" will be executed.
See `org.postgresql.pljava.example.annotation.ConditionalDDR` for an example/test.
If this seems mostly like an …
> Deployment descriptor conditionals as proposed on pljava-dev.

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/UnicodeRoundTripTest.java
- pljava-examples/src/main/resources/deployment/examples.ddr
- pljava-so/src/main/c/JNICalls.c
- pljava-so/src/main/c/type/String.c
- pljava-so/src/main/include/pljava/JNICalls.h
With this pull request I am hoping to start a tradition where a pull request for a bug will have a _first_ commit that only adds a testcase ... so the testcase should then fail, and the remaining commit(s) should make it pass.
I'd be happy to rebase this PR on top of #56 deployment descriptor conditionals if that gets merged first. The testcase added here uses `ORDER BY` inside `array_agg` and `string_agg` which will be a syntax error before PG 9.0 ... a perfect occasion to use DDR conditionals ....
Closes #21.
> Pass all Unicode codepoints transparently (issue #21).

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Enumeration.java
- pljava-so/src/main/c/type/String.c
I opted not to always pass `typeId` in place of `elementType` to the input function (r0ml's solution), but instead to assign the `typeId` to `elementType` at creation (instead of zero), in the case that the type being mapped is an enum. Not sure it matters, but seemed a more conservative change.
> Fix oldest outstanding github issue, enum support.

- pom.xml
Apparently nothing is needed any more from repositories declared
at nexus.tada.se - my builds complete faultlessly with these repository
declarations removed. On the other hand, when they are present, they
will hang a maven build if the nexus.tada.se server can't be contacted,
which has been a lot of the time lately.
> Remove nexus.tada.se references from POM.

- pljava-so/src/main/c/type/Type.c
Ken Olson pointed this out as a case of 'dead code', but in fact it was live use of an unassigned variable just _before_ the function call that was going to assign it. Had to be an editing mixup, has been that way a very long time, and has probably not caused more problems only because it's statistically rare for a random stack location to be exactly equal to `InvalidOid`.
Scratches the surface of #65. A full solution for that issue will have to come later, but this much was an obvious Heisenbug with an obvious fix.
> Type_getCoerceOut correct statement order.

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ThreadTest.java
- pljava-so/src/main/c/ExecutionPlan.c
- pljava-so/src/main/c/SPI.c
- pljava-so/src/main/c/type/Portal.c
- pljava-so/src/main/include/pljava/pljava.h
set_stack_base() and restore_stack_base() were added in preference to
direct access to stack_base_ptr (for 9.2, backpatched into 9.1.4,
9.0.8, 8.4.12, and 8.3.19). This adapts PL/Java to that new API so PostgreSQL
doesn't have to keep the old one around forever.
The new style requires miscadmin.h to be included
in those source files that use the STACK_BASE_PUSH / STACK_BASE_POP
macros (there is so much in miscadmin.h, I did not want to add it in
pljava.h and have it processed everywhere).
Also added example ThreadTest.java just to exercise the new logic.
However, if enabled to run from the deployment descriptor, it does
deadlock; apparently PG -> J -> (otherthread PG) works, but the deeper
PG -> J -> PG -> J -> (otherthread PG) does not, and I *suspect* it's
because of the JNI warning …
> Track PostgreSQL's changes to stack base access.

- pom.xml
Reported by dblanch: mvn site site:stage  can fail in newer Maven versions, with `java.lang.NoClassDefFoundError: org/sonatype/aether/graph/DependencyFilter`
The explanation is here:
https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound
Solution requires updating to `maven-site-plugin` >= 3.3.  3.4 is current
and works for me, so it is now specified.
> Track upstream maven-site-plugin.

- packaging/build.xml
- pljava-so/build.xml
- pljava-so/pom.xml
In the nar-maven-plugin, `shared` and `plugin` are interchangeable on
platforms other than Darwin, but on Darwin they produce two different
link commands (a `plugin` gets the `-bundle` option).
The distinction (on Darwin) is a shared object is something exporting
some API that the process loading it will call into, but a plugin/bundle
also expects to be able to call *back* into API provided by the thing that
loaded it. PL/Java fits in the second category, so may as well call it a
plugin; won't change much on other platforms, but makes a difference on
Darwin.
When linking a plugin, the Darwin linker wants the `-bundle_loader` option
to identify the program that will be loading the plugin (postgres, in
this case). It verifies that the symbols unresolved in the plugin itself
really will be …
> Resolve OS X build problems (issue 63).

- packaging/pom.xml
- pljava-ant/pom.xml
- pljava-api/pom.xml
- pljava-deploy/pom.xml
- pljava-examples/pom.xml
- pljava-so/pom.xml
- pljava/pom.xml
- pom.xml
For a couple of years it has been 0.0.2-SNAPSHOT, not even in the same
sequence as PL/Java versions before moving to Maven. Fix it to
accurately show that this snapshot is on the way to a 1.5.0 release.
> Alter project version to 1.5.0-SNAPSHOT.

- pljava-so/src/main/include/pljava/Exception.h
In PG commit bbfd7eda, uses of compiler `__attribute__` marks were
replaced by new dedicated-purpose macros like `pg_attribute_printf`,
appearing in 9.5+. Adapt to the new style, in the one file where
the old style was used.
Caught by Ken Olson, on Windows MSVC, where it broke.
> Track PG9.5 change re compiler attributes.

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
Earlier in the week I saw truly perplexing errors that stemmed
from a simple missing or misspelled import, but javac, instead
of reporting the error, would supply DDRProcessor with an instance
of an internal Error class where the unresolvable value should have
been. So now, at least recognize that Error class and produce a more
helpful message. Now, of course, I am unable to test the change,
because javac (same version! same machine!) is now doing the right
thing every time. At least with this change, if the right conditions
are ever hit again for javac to misbehave as it was earlier, the
message should be more helpful.
> Improve message in strange javac error case.

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/include/pljava/InstallHelper.h
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- src/site/markdown/use/variables.md
Make the cluster name easily available if it is set (to a
nonempty string, in PostgreSQL versions where it is available),
as a java system property and in the title visible to jps
and jvisualvm.
In passing, lose the default vmoption to lock out jvisualvm local
connections. Noah Misch persuades me that PostgreSQL itself doesn't
make special efforts to prevent things that already require access
as the postgres user on the server host, and it would be unpostgresy
to do so here. Instead, simply document how to disable attachment,
if the admin so desires.
> Cluster name as property and in jps title.

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/Exception.c
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/include/pljava/pljava.h
Move a bunch of DEBUG1s to DEBUG2, leaving DEBUG1 for the
initial load message that identifies PL/Java and JVM versions.
(This is NOTICE if PL/Java is explicitly LOADed, so it's seen
by default, but in other cases you can now see it by enabling
DEBUG1, and not mixed in with a lot of other stuff.)
> Make DEBUG1 quieter.

- pljava-api/src/main/java/org/postgresql/pljava/annotation/BaseUDT.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/Function.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/MappedUDT.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLType.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/Trigger.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/package-info.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
Bit of a luxury perhaps, but the last thing left on the list I sent around on December 18th.
Get the SQL generator producing SQL comments where possible from user code, and exploit that to get most comments on PL/Java's own objects too, with a few of the rest hand-coded.
There is no new thing under the sun; László Hornyák had PL-J making comments out of javadoc some time back in 2004 or '05.
> SQL comments on PL/Java's own DB objects, and user generated ones.

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Function.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/c/SPI.c
- pljava-so/src/main/c/type/Composite.c
- pljava-so/src/main/c/type/Portal.c
- pljava-so/src/main/c/type/TupleDesc.c
- pljava-so/src/main/c/type/TupleTable.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/include/pljava/InstallHelper.h
- pljava-so/src/main/include/pljava/pljava.h
- pljava-so/src/main/include/pljava/type/Type.h
- pljava-so/src/main/include/pljava/type/Type_priv.h
- pljava/src/main/java/org/postgresql/pljava/internal/Portal.java
- pljava/src/main/java/org/postgresql/pljava/internal/SPI.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIPreparedStatement.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIStatement.java
- src/site/markdown/use/parallel.md
- src/site/markdown/use/use.md
Catch up with various changes in PostgreSQL 9.6, including the widening to 64 bits of various things related to row counts, the consequent demise of `Portal`'s `posOverflow` flag, and the final removal of `heap_formtuple` (which was deprecated for a long time, with the preferred alternative already present back at least as far as 8.2).
PL/Java can now be used in PostgreSQL 9.6 parallel queries (and for other purposes in background worker processes, which were introduced in 9.3, but only supported from 9.5 on in PL/Java).
A [wiki page](https://github.com/tada/pljava/wiki/Parallel-query-and-PLJava) has been added about the parallel capabilities.
Should resolve #108.
> Bring PostgreSQL 9.6 compatibility.

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/include/pljava/InstallHelper.h
- src/site/markdown/install/install.md.vm
- src/site/markdown/install/upgrade.md
- src/site/site.xml
As reported in #117, PL/Java's self-installing behavior steps on the toes of `pg_upgrade`. It is explicitly caught by a check Bruce Momjian added to `pg_upgrade` [for PG 9.5][upchk], but even if an earlier PG version doesn't catch it, it still could cause OID and duplicate-object clashes, and PL/Java should refrain from doing it when a `pg_upgrade` is in progress.
This is also a good opportunity to expand the doc of upgrade procedures to a whole page of its own.
Will take care of #117 when released.
[upchk]: https://git.postgresql.org/gitweb/?p=postgresql.git;a=blobdiff;f=src/backend/catalog/heap.c;h=c346edac93be55889e8fe18398579be551ce0f5f;hp=33eef9f1caffcfbcd178140047d1ef64abb5145c;hb=a7ae1dcf4939cf643c5abe8dd673e4b87a6efd42;hpb=73fe87503f23144a27f0bdecc55587deb5aa425f
> Bug/rel1 5 stable/pg upgrade

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Trigger.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Triggers.java
- pljava-so/build.xml
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/Invocation.c
- pljava-so/src/main/c/type/Time.c
- pljava-so/src/main/c/type/Timestamp.c
- pljava-so/src/main/include/pljava/Backend.h
- pljava-so/src/main/include/pljava/Invocation.h
These PostgreSQL 10 changes affect PL/Java. (This list may not be complete, but these are the ones addressed here.)
New version number format (requires change to a regexp in PL/Java's build process).
Demise of non-integer datetimes (renders some PL/Java code dead, with warnings).
Transition tables (new trigger feature, now supported and with SQL generation).
> Changes to accommodate PostgreSQL 10.

- pljava-so/build.xml
- pljava-so/pom.xml
- pljava-so/src/main/c/Backend.c
- src/site/markdown/build/build.md
- src/site/markdown/build/package.md
- src/site/markdown/install/install.md.vm
- src/site/site.xml
Add some command-line options for the `mvn` build or the `java` self-extracting jar invocation, to specify things for which at least one downstream package maintainer had patched the sources instead. Also add a new documentation page especially for package maintainers.
> New build/install options and documentation for downstream packagers

- pljava/src/main/java/org/postgresql/pljava/internal/ELogHandler.java
- src/site/markdown/examples/examples.md.vm
- src/site/markdown/releasenotes.md.vm
Fix the easier complaint in issue #125; if Java will be summarily
discarding log messages finer than a level derived from PostgreSQL's
settings just once at PL/Java startup, at least derive the level
from the finer of `log_min_messages` and `client_min_messages`, rather
than from `log_min_messages` alone.
> Honor client_min_messages too at PL/Java startup.

- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java
Fix #136 SPIConnection prepareStatement doesn't recognize all parameters when SQL combines single and double quotes
> Fix #136 SPIConnection prepareStatement doesn't recognize all parameters

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Trigger.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Triggers.java
Constraint triggers can be declared and are usable (the runtime will deliver them; a trigger method should throw an exception to report that a constraint would be violated); however, the `TriggerData` interface has not been extended to expose any of the new contraint-trigger-specific information to the called method. There's a redesign of that PL/Java API in the works, ideally to better use the type system to reduce the sanity checking currently needed in trigger methods, which can increase when upstream adds new types of events, putting already-written trigger methods at risk. Exposing the constraint-specific information would fit well as part of that work, probably for a major release after 1.5.x.
> Allow SQL generation for constraint triggers.

- pljava-api/src/main/java/org/postgresql/pljava/ResultSetHandle.java
- pljava-api/src/main/java/org/postgresql/pljava/ResultSetProvider.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SetOfRecordTest.java
- pljava-examples/src/main/resources/deployment/examples.ddr
- pljava/src/main/java/org/postgresql/pljava/jdbc/SingleRowWriter.java
- src/java/test/org/postgresql/pljava/test/Tester.java
Cast types as expected if the types in the supplied `ResultSet` differ from those in the calling query's column definition list. Addresses issue #146. Adds a test and expanded API documentation.
> Handle SETOF RECORD better in ResultSetHandle

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ComplexTuple.java
- pljava/src/main/java/org/postgresql/pljava/internal/Oid.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIPreparedStatement.java
Provide one of the short-term solutions suggested in issue #149.
As the current PreparedStatement implementation does not get the
inferred parameter types from PostgreSQL (which became possible
with SPI only as recently as PostgreSQL 9.0), its setObject method
must make a best effort to map in the other direction, finding the
PostgreSQL type that corresponds to the Java parameter value. In
one case, this is easily made much more reliable: when the Java
parameter value is an SQLData instance (a UDT), and therefore has
a getSQLTypeName method, unused until now.
Add a test method (in the ComplexTuple UDT example) to confirm that
the type is properly mapped when passed as a parameter to a
PreparedStatement.
> Use getSQLTypeName, one minor change suggested in issue #149

- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLType.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/RecordParameterDefaults.java
PL/Java has long had the ability to declare a function parameter that is of a row type, even of the row type `RECORD` with no _a priori_ known structure. This is quite convenient for implementing functions that can be passed an arbitrary sequence of named, typed parameters by the SQL caller.
This patch tweaks the SQL deployment descriptor generator to be able to emit default values for parameters of row types (where previously it could only emit working syntax for scalars or arrays). This simplifies the development of functions accepting _optional_ sequences of arbitrary named, typed parameters.
Adds `RecordParameterDefaults.java` in `pljava-examples` for illustration.
> Let annotations give defaults to row-type parameters.

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/TypeRoundTripper.java
- pljava-so/src/main/c/type/Timestamp.c
The C code was failing to preserve the invariant that the `nanos` component of the Java Timestamp representation is never negative, no matter the sign of the millis-from-epoch component, and was also double-counting the millisecond portion of the fractional second (which is represented both in the millis-from-epoch and in the nanos component).
Adds a test class and tests to confirm the fixed behavior.
In passing, adds `PG_VERSION_NUM` conditionals to reduce the cost of timezone retrieval in MSVC in versions where the variable has been made accessible.
> Correct timestamp/timestamptz as reported in #155

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Parameters.java
- pljava-examples/src/main/resources/deployment/examples.ddr
The annotation processor was failing to register a mapping of Java `byte[]` to SQL `bytea` as intended (issue #157), because the code assumed a `TypeElement` could be created from the name of an array type, which turns out not to be the case. It is necessary to first make a `TypeMirror` representing the component type, then wrap that in the right number of `ArrayType`s.
None of the existing annotation examples covered the cases of `bytea` parameter or return types. The non-annotation example `Parameters.java` did, and is now an annotation example so future regressions can be caught.
This patch also eliminates a long-standing mysterious warning from the annotation processor that had not been pursued because of the lack of problem reports.
> Fix SQL generator failure to map byte[] to bytea

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ComplexScalar.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ComplexTuple.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/IntWithMod.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Point.java
It was never satisfying to define a UDT in Java through annotations
and still have the DDR generator give "no mapping to an SQL type" errors
for functions accepting or returning that type. It was easy enough (if
tedious) to work around by adding explicit `type=` or `@SQLType` annotations,
but the DDR generator had all the necessary information to figure that out
without such manual help. Now it does so, eliminating the tedium
illustrated in jcflack/pljava-udt-type-extension@bcb5734.
To accommodate mappings added from the source being compiled, the
protoMappings collection is now of TypeMirror instances rather than
of Class instances.
Still future work: also add implied ordering dependencies for uses of
the new type (such as functions that have it as parameter or return
types and have to …
> Improve DDR generator on the dont-repeat-yourself dimension for UDT type mapping.

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/type/JavaWrapper.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/include/pljava/pljava.h
- src/site/markdown/releasenotes.md.vm
- src/site/markdown/use/variables.md
Thanks to Luca Ferrari who in #160 presented both of these patches that allow PL/Java to build and deploy the examples jar without problems in PG 11. This PR includes both patches, and I have also just gone through the PG 11 release notes looking for other possible trouble spots, and saw nothing obvious. Perhaps nothing more will be needed.
> Add support for PostgreSQL 11 (beta2).

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRWriter.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ConditionalDDR.java
The implicitly-added provides/requires relationships between implementor
tags and the snippets that test the environment to activate or suppress
them need to be treated specially. Unlike other dependency
relationships, which have their sense reversed between the INSTALL and
REMOVE action groups, these implicit ones need to keep the same sense.
It always works better to test a condition before needing to use the
result.
The old augmentRequires method, which created the implied dependencies
by outright adding them to the snippet's other requires, is now gone;
the implied relationship is simply handled within the ordering code.
Two DAGs are created, one for install and one for remove, and an order
is found independently for each.
It's also necessary to use the deployStrings of tag-testing …
> Emit REMOVE section of DDR in right order (#163).

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ConditionalDDR.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Enumeration.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/IntWithMod.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PGF1010962.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/RecordParameterDefaults.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SetOfRecordTest.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Triggers.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/TypeRoundTripper.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/UnicodeRoundTripTest.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/VarlenaUDTTest.java
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/include/pljava/InstallHelper.h
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
A recent pull request added (with apparent success) PostgreSQL 11 support, and meanwhile `versions.md` for this, the 1.5.x branch, still says the "current aim is to avoid deliberately breaking compatibility back to 8.2."
That's a wide range of PG versions, and without a buildfarm regularly testing against them, some issues have found their way in to thwart building with some of those releases. (Additions to PL/Java itself not tested against all those PG versions can have that effect, as can PostgreSQL changes getting backpatched into old versions that were supposed to have worked.)
The next _major_ release of PL/Java is sure to drastically curtail the number of ancient PostgreSQL versions supported. That is another reason to undertake this chore on the 1.5 branch; it's good, before the …
> Actually check all PG major versions for which support is claimed.

- pljava-so/src/main/c/Backend.c
The call to InitializeTimeouts here was probably added based on
a quick reading of the code comment in PG's timeout.c, where it
says "This must be called in every process that wants to use timeouts."
But it has been called already in a backend process (PostgresMain
did that), and calling it again here is not necessary or correct.
> Do not clobber timeouts when loaded (#166).

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Holdability.java
- pljava-so/src/main/c/Invocation.c
- pljava-so/src/main/c/type/Portal.c
- pljava/src/main/java/org/postgresql/pljava/jdbc/ResultSetBase.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIDatabaseMetaData.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SingleRowResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SingleRowWriter.java
There were several comments scattered through the code saying PL/Java's `ResultSet`s were unusable after function return, even though they would report holdability of `CLOSE_CURSORS_AT_COMMIT`.
That was true, but only because of a couple of missing `Invocation_assertConnect` calls, so insert those, and update the old pessimistic comments.
> Give ResultSets actual CLOSE_CURSORS_AT_COMMIT holdability (issue 168)

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/DualState.c
- pljava-so/src/main/c/Invocation.c
- pljava-so/src/main/c/JNICalls.c
- pljava-so/src/main/c/VarlenaWrapper.c
- pljava-so/src/main/c/type/Oid.c
- pljava-so/src/main/c/type/Portal.c
- pljava-so/src/main/c/type/SQLXMLImpl.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/include/pljava/DualState.h
- pljava-so/src/main/include/pljava/JNICalls.h
- pljava-so/src/main/include/pljava/VarlenaWrapper.h
- pljava/src/main/java/org/postgresql/pljava/internal/ByteBufferInputStream.java
- pljava/src/main/java/org/postgresql/pljava/internal/DualState.java
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pljava/src/main/java/org/postgresql/pljava/internal/MarkableSequenceInputStream.java
- pljava/src/main/java/org/postgresql/pljava/internal/Session.java
- pljava/src/main/java/org/postgresql/pljava/internal/VarlenaWrapper.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/AbstractResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/MarkableSequenceInputStream.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIDatabaseMetaData.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIPreparedStatement.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLInputFromTuple.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLOutputToTuple.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
This type has been unsupported in PL/Java until now, despite being specified in JDBC since version 4 and Java 6 and despite PostgreSQL having an XML type since PG 8.3.
It has not been impossible for PL/Java functions to work with XML data; the default mappings have allowed accessing a value of XML type as a `String` object. But that's an extra porting burden on code developed with the standard API in mind, can risk either unexpected errors or silent corruption for some combinations of character encoding settings, and also has memory implications.
While a database design using XML may be such that each XML datum is individually small, it is also easy to store—or generate in queries—large XML values. When mapped to a Java `String`, every XML value ends up with its full, uncompressed, …
> Support the JDBC 4.0 SQLXML type.

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIDatabaseMetaData.java
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/EntryStreamHandler.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/Loader.java
- src/site/markdown/releasenotes.md.vm
Rather tedious to do, and perhaps obsessive in any database where the [recommended steps][prot] have been taken to protect from CVE-2018-1058, but adds a measure of defense-in-depth in case they have not.
No changes in `pljava-examples`; if the examples jar will be installed, it should be in a database where the recommended steps have been followed.
[prot]: https://wiki.postgresql.org/wiki/A_Guide_to_CVE-2018-1058:_Protect_Your_Search_Path#Next_Steps:_How_Can_I_Protect_My_Databases.3F
> Schema-qualify objects in queries/DDL PL/Java generates internally.

- pljava-packaging/build.xml
Addresses issue #179.
What apparently happened in some OpenJDK 6 and 7 packages was that it was left to the packager to obtain (or not) the [Rhino JavaScript engine][rhino] and, separately, the wrapper layer that presents it through the `javax.script` API. It's not clear whether there is a single, authoritative, open source for that wrapper layer (see, for example, [here][w1] and [here][w2], of which the second is more up to date, but both have problems). Among the things incomplete in these wrappers are conversions to Java `String` from some implementation factors of JavaScript `String`. The obvious cases are handled, but Rhino in some cases will have a JavaScript String represented by a `ConsString` instance, which is not treated by the wrapper as a String.
Using the ConsString to …
> Avoid self-install jar failure on certain Rhino-based JavaScript engines.

- pljava-api/src/main/java/org/postgresql/pljava/annotation/package-info.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
When true, it constrains the order of the generated DDR to be
consistent over successive compilations of the same sources,
useful in distribution builds where reproducibility is valued.
When false, it selects the previous behavior, where descriptors
can have different order from one compilation to the next of the
same sources; during testing, this can help to detect whether
there are necessary provides/requires relationships that haven't
been declared.
Addresses issue #181.
The 'reproducible' option also makes deterministic the order of Java-to-SQL
type mappings known to the generator, though this is an internal
detail; the ordered mappings are not emitted explicitly into the
DDR, and if a change in their order would affect what is written
there, that would probably indicate a more …
> Add a ddr.reproducible option to SQL generator.

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/InstallHelper.c
Thanks to Ken Olson for the reminder that the Windows MSVC compiler
won't accept conditional-compilation syntax within an invocation
of a preprocessor macro. 5e01f8f was already about that, but a few
uses have crept back in through my inattention.
Honestly, MSVC is doing a service here, as a quick check of the
standard shows that preprocessing directives within macro invocations
really do have undefined behavior. Addresses issue #182.
> No really, avoid #if among macro arguments.

- pljava-examples/pom.xml
Saxon 9.9 is out, but some API has changed, so it is not drop-in. For now, simply exclude the new version; the API can be adapted later.
Addresses issue #185.
> Exclude Saxon 9.9 for now.

- pljava-so/src/main/c/VarlenaWrapper.c
Addresses issue #177.
The size of `Size` can be architecture-specific and differ from that of `jlong`. When writing JNI calls to Java methods, one is essentially performing without a net; the JNI method invocation functions take C variable arg lists, and the C compiler has no information for checking the types of the passed parameters against the signature of the method.
It would not be a bad thing to come up with a way to statically check those calls.
> Avoid segfault in VarlenaWrapper.Input on 32-bit.

- pljava-examples/src/main/java/org/postgresql/pljava/example/jdk7/TypeRoundTripper.java
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/type/Oid.c
- pljava-so/src/main/include/pljava/Function.h
- pljava/src/main/java/org/postgresql/pljava/internal/Oid.java
Addresses issue #192.
`Oid.getJavaClass` had been using the class loader that loaded `Oid` itself, which is on `pljava.classpath`; its loader cannot see classes in user-loaded jars on the schema classpath.
Add a `Function_getCurrentLoader()` to retrieve a saved reference to the initiating loader used to find the function's containing class. That should be the "schema loader" for the schema in which the function is declared. Tempting to cheat and just use `getClassLoader` on the function's class, but that would return the defining loader, in cases where it and the initiating loader are different.
The choice to use the schema loader for the innermost executing PL/Java function is for consistency with the documented convention (in the developer notes) of using the innermost executing …
> Use schema class loader in OId.getJavaClass

- src/site/markdown/build/versions.md
- src/site/markdown/releasenotes.md.vm
Handle some platforms (*cough* Windows *cough*) where the write-as-temp-file-then-rename technique is complicated by the inability to rename over an existing file.
Addresses issue #189.
> Detect installer jar failure to rename over existing file.

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SetOfRecordTest.java
The SetOfRecordTest is only there to demonstrate that sets of RECORD
can be returned, and that casts are done from a ResultSetHandle as
needed. Using a timestamp as one of the test values can make it also
(in some circumstances) a demonstration of java.sql.Timestamp's
unintuitive dependence on local time zone settings ... which is why
the JDBC 4.2 mapping to java.time.LocalDateTime is preferable, which
the documentation and release notes already explain. The purpose of
SetOfRecordTest can be achieved just as well using types that don't
have that sort of environment dependency.
Addresses issue #195.
> Avoid timestamp in SetOfRecordTest.

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PreJSR310.java
- pljava-so/src/main/c/type/Date.c
- src/site/markdown/releasenotes.md.vm
- src/site/markdown/use/datetime.md
Fix a regression in 1.5.1 that was not caught in pre-release testing, and could leave conversions between PostgreSQL `date` and `java.sql.Date` off by one day in certain timezones and times of the year (#199).
1.5.1 added support for the newer `java.time` classes from JSR 310 / JDBC 4.2, which are [recommended as superior alternatives][migrate] to the older conversions involving `java.sql.Date` and related classes. The new versions are superior in part because they do not have hidden timezone dependencies.
However, the change to the historical `java.sql.Date` conversion behavior was inadvertent and needs to be fixed.
Other issues in date/time conversion have also been uncovered that are of longer standing, not recent regressions. They are detailed in #200 and are not fixed in this PR, but …
> Fix 1.5.1 regression in date conversion to/from java.sql.Date

- pljava-examples/src/main/java/org/postgresql/pljava/example/Triggers.java
- pljava-examples/src/main/resources/deployment/examples.ddr
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/c/type/AclId.c
- pljava-so/src/main/c/type/Time.c
- pljava-so/src/main/c/type/Timestamp.c
- pljava-so/src/main/c/type/TupleTable.c
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIDatabaseMetaData.java
With the changes on this branch, PL/Java builds and passes tests for PG 12 beta1, as well as all PG versions already supported by the PL/Java 1.5.x series.
> Support PostgreSQL 12

- pljava-api/src/main/java/org/postgresql/pljava/ObjectPool.java
- pljava-api/src/main/java/org/postgresql/pljava/Session.java
- pljava/src/main/java/org/postgresql/pljava/internal/ExecutionPlan.java
- pljava/src/main/java/org/postgresql/pljava/internal/ObjectPoolImpl.java
- pljava/src/main/java/org/postgresql/pljava/internal/Oid.java
- pljava/src/main/java/org/postgresql/pljava/internal/Session.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/ObjectResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIPreparedStatement.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLInputFromTuple.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLOutputToTuple.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SingleRowWriter.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SyntheticResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/TriggerResultSet.java
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/Loader.java
A solid, if non-exhaustive, effort to bring the code up to date with
Java generics and transparent boxing/unboxing, based on a simplistic
mechanical search for places where unnecessary explicit casting/boxing/
unboxing was being done.
In the files touched, also elide a bunch of 'this.' qualifications on
instance method calls. And fix the spelling of 'Coercion' in three methods.
Bonus: fix three very old thinkos in SPIPreparedStatement that no one
ever seems to have run into or reported.
> Adopt generics in more places where applicable.

- pljava-so/build.xml
- pljava-so/pom.xml
- pljava-so/src/main/include/fallback/jdbc/java_sql_Types.h
- pljava/pom.xml
- pom.xml
- src/site/markdown/build/build.md
- src/site/markdown/build/versions.md
To this point, PL/Java 1.5.x has required a Java 8 (or 7, or with considerable nursing, 6) JDK to build, though it can then run on later JREs (and user code can be written to the later language standards and APIs). Java 9 introduced changes that threatened to be hard to work into the build system while preserving 1.5.x's ability to be built in the older environments. The original plan was to keep the 1.5.x build requirements unchanged, and make the next major version purely Java 9 and later (and drop some of the ancient-PG-release support as well).
But issue #212 raised the stakes, as apparently Debian distros are out now or imminently that won't have a Java 8 development kit handy for package building. So, this PR tweaks 1.5.x as minimally as possible with the aim of _allowing_ it to be …
> Allow 1.5 series to build with Java 9 and later

- pljava-so/src/main/c/PgSavepoint.c
Only caught when tested in PG 9.6 or earlier, because the function
was already a no-op upstream since PG 10 (postgres/postgres@1833f1a).
Addresses issue #221.
> One line missed in finalizers refactoring

- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLType.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/Lexicals.java
The SQL generator has been emitting `CREATE FUNCTION` with parameter
names that match the Java names of the function parameters, so that
the SQL functions can be called with named-parameter notation.
But there can be cases when a different SQL name is wanted for the
parameter, whether because the Java name happens to be a reserved
SQL word, or because a particular SQL parameter name is wanted (comes
from a standard, maybe?) and happens to be a reserved Java word,
or just because.
Further overload the per-parameter `@SQLType` annotation (which is
already a little overloaded and misnamed, being able to supply
default values as well as type information) with a `name` property,
which can be a regular identifier or a delimited one (in case a
parameter name is really wanted with the same …
> Allow a parameter's SQL name to be explicit.

- pljava-api/src/main/java/org/postgresql/pljava/SavepointListener.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SPIActions.java
- pljava-examples/src/main/resources/deployment/examples.ddr
- pljava-so/src/main/c/Invocation.c
- pljava-so/src/main/c/SubXactListener.c
- pljava/src/main/java/org/postgresql/pljava/internal/PgSavepoint.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/Invocation.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java
Addresses issue #228.
Per JDBC, a `Savepoint` still exists after being used in a `rollback` and can be used again, while only those `Savepoint`s created after it are invalidated by the rollback.
That behavior should be familiar, as it is the same as PostgreSQL's own SQL `SAVEPOINT` behavior. It is also found in pgJDBC, which has test coverage to confirm it.
PL/Java has been doing it wrong for a long time, because the behavior of PostgreSQL's "internal subtransaction" API is different, and that's the API that has to be used inside of a function. Those things are used up after a rollback.
Getting the right behavior simply requires transparently establishing a new "internal subtransaction" as the last step of a JDBC `Savepoint` rollback. That will be a behavior change, but largely …
> Provide correct JDBC Savepoint behavior

- pljava-api/src/main/java/org/postgresql/pljava/Adjusting.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
- src/site/markdown/use/sqlxml.md
Introduce a class in `pljava-api`, `org.postgresql.pljava.Adjusting`.
It serves as a namespace that will contain member classes/interfaces intended for adjusting various categories of PL/Java behavior. The first such member class will be `XML` and provide a small fluent API to use with the `SQLXML` implementation for adjusting XML parser features/restrictions.
The idea is to encourage a single `import org.postgresql.pljava.Adjusting;` to bring in the top-level class, just to be able to say things like:
```java
SAXSource src = sqx.getSource(Adjusting.XML.SAXSource.class)
.allowDTD(true).expandEntityReferences(true).get();
```
Without such an API, the traditional methods in Java to tweak such parser settings are so onerous and fiddly (not to mention, in some cases, inaccessibly concealed …
> Start a convention for micro-APIs that adjust particular categories of behavior

- pljava-api/src/main/java/org/postgresql/pljava/Adjusting.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava-so/src/main/c/type/SQLXMLImpl.c
- pljava/src/main/java/org/postgresql/pljava/internal/DualState.java
- pljava/src/main/java/org/postgresql/pljava/internal/MarkableSequenceReader.java
- pljava/src/main/java/org/postgresql/pljava/internal/VarlenaWrapper.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/XMLEventToStreamConsumer.java
- src/site/markdown/use/sqlxml.md
It should be possible for a PL/Java function to use another JDBC driver connected to another database, obtain an `SQLXML` object from that (which will not, of course, be PL/Java's implementation), and return or pass that to PostgreSQL. That simply requires detecting that an instance of `SQLXML` isn't an instance of PL/Java's implementing class, and transparently creating a new empty one that is and copying the content to it. The foreign one must, of course, be in 'readable' state, and willing to provide its content as one of: `StreamSource`, `SAXSource`, `StAXSource`, or `DOMSource` (its `getSource` method will be passed `null`, so it gets to choose which of those flavors it prefers to provide).
> Accept SQLXML objects from other JDBC drivers

- pljava-examples/pom.xml
- pljava-examples/src/main/java/org/postgresql/pljava/example/saxon/S9.java
- pom.xml
Follow-on to PR #222. When building with Java 9 or later, it is possible to use `--release` to specify the target runtime release, replacing the older `-source` and `-target`. But more than "possible", it is _necessary_ to do so, as otherwise API changes in Java 9 will get baked into the compiled classes, causing even unchanged Java 6 compatible source code to compile to classes that will throw link errors in a pre-Java-9 runtime.
> Allow 1.5 to build with Java 9 or later, and work earlier

- pljava-examples/pom.xml
- pljava-examples/src/main/java/org/postgresql/pljava/example/saxon/S9.java
- src/site/markdown/examples/examples.md.vm
- src/site/markdown/examples/saxon.md
While still presented as example rather than production code (and lacking, for example, a test suite), the optionally-built `org.postgresql.pljava.example.saxon.S9` example is intended as a substantially usable implementation of `XMLCAST`, `XMLQUERY`, `XMLTABLE`, and the five XQuery regular-expression-based operations `LIKE_REGEX`, `OCCURRENCES_REGEX`, `POSITION_REGEX`, `SUBSTRING_REGEX`, and `TRANSLATE_REGEX` ... as well as `XMLTEXT`, which is trivial and has no need of an XQuery library, but is missing from core PostgreSQL and easy to supply here for completeness.
As ordinary extension functions unabetted by parser modifications, these all require some straightforward rewriting of what would be the standard SQL forms into equivalent forms that should be easily readable, while conforming …
> Complete (fsvo "complete") the Saxon-based XQuery examples

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/DualState.c
- pljava-so/src/main/c/Invocation.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/include/pljava/DualState.h
- pljava/src/main/java/org/postgresql/pljava/jdbc/Invocation.java
A couple bugs not reported from the field but noticed in the rampdown to 1.5.3.
One involves the relatively recent addition of the `DualState` class and only affects behavior when PL/Java's startup fails.
One has been around much longer, in the management of SPI connections for set-returning functions, but is easier to expose with the heavier use of composite-parameter-and-return-typed functions in the recently added example code.
> Bugs caught ramping down to 1.5.3

- pljava-deploy/src/main/java/org/postgresql/pljava/deploy/Deployer.java
- pom.xml
As reported in #239, javadoc with an 11 or newer JDK can
fail with a message about code in modules being linked to
Java API code in the unnamed package. The Java bug report
indicates a fix was rolled out (adding code to detect when
the 'module' being detected is really an automatic module),
but it seems a `<source>` element in the configuration of the
`maven-javadoc-plugin` is still needed. That will just specify
a hardcoded 8 for now (even if the `--release` given to `javac`
will be 7 or 6); javadoc doesn't seem to mind if it is not
an exact match. (Even an actual javadoc 7 seems not to object
to source 8.)
In passing: with that hurdle cleared, javadoc 12 proceeds to
complain about non-HTML5 attributes in `Deployer`'s javadoc, so
those are removed here (even though `Deployer` itself is …
> Fix a Javadoc build issue with Java 11+

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
As reported in issue #235, the `--release` option in newer `javac`
versions will check against a `ct.sym` file included in the jdk
that is meant to record what API was available in which prior
releases, and that file (at least as shipped in Java 11) is
missing the `newFactory()` methods on `XMLInputFactory` and
`XMLOutputFactory` for release 6, so it reports them not found.
Happily, both no-arg `newFactory()` methods are equivalent to
the no-arg `newInstance()` methods. Deprecation tags were added
to the `newInstance(String,ClassLoader)` methods, but not to
the no-arg ones.
> Sop for javac's --release 6 check

- pom.xml
This seems to be a minimal sufficient change to build successfully
with Java 13, avoiding the `ArrayIndexOutOfBoundsException` reported
in #236.
> Fix array-index exception in Java 13 build

- pljava-api/src/main/java/org/postgresql/pljava/Adjusting.java
- pljava-deploy/src/main/java/org/postgresql/pljava/deploy/Deployer.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/saxon/S9.java
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
- pom.xml
For Java 13, the version of the `maven-javadoc-plugin` must be
advanced to avoid pulling in a version of `commons-lang` whose
`getJavaVersionAsFloat()` method is broken by a change to the
version property values reported in 13.
There seems to be no choice of `maven-javadoc-plugin` version
that will work with 13 and also back to 6, so use profiles
based on the build-time JDK version to select the plugin version
to use.
A benefit of advancing the `maven-javadoc-plugin` version is that
the `<source>` element added in a28db9f can be removed again, as the
newer plugin does not need it.
Javadoc 13 is more strict in checking HTML5 structure, and disallows
`<h1>` in a doc comment (a level-1 header is generated by Javadoc itself),
requiring `h` elements to be used in proper sequence with `h2` …
> Allow Javadoc to build with Java 13

- pljava/src/main/java/org/postgresql/pljava/internal/DualState.java
- pljava/src/main/java/org/postgresql/pljava/internal/VarlenaWrapper.java
It is not necessary for `pinUnlessReleased` to throw any checked exception, so remove the `throws` clause, simplifying callers.
Although not likely and not seen in practice, there's a conceivable race condition between explicit `releaseFromJava()` and unreachability detected by GC, depending on when code doing the explicit release last holds a strong reference. The case may never arise, but should be handled gracefully if it does.
> Tweaks from another review pass over DualState

- pljava-so/src/main/c/Invocation.c
Code added to PgSavepoint.onInvocationExit() in 53aaa42 relies on executing in the PG thread; don't relinquish the monitor in the upcall from C. This should have been included in PR #229.
> One change left out of PR #229

- pljava-so/src/main/c/ExecutionPlan.c
- pljava-so/src/main/c/JNICalls.c
- pljava-so/src/main/c/PgSavepoint.c
- pljava-so/src/main/c/VarlenaWrapper.c
- pljava-so/src/main/c/type/ErrorData.c
- pljava-so/src/main/c/type/Relation.c
- pljava-so/src/main/c/type/TriggerData.c
- pljava-so/src/main/c/type/Tuple.c
- pljava-so/src/main/c/type/TupleDesc.c
The big refactoring in PR #206, away from finalizers and to the `DualState` class, introduced a few places where a C `long` or pointer to be represented as a Java `long` (which is how the resource owner is handled when constructing an object based on `DualState`) was not properly widened to `jlong`. That only affected architectures where a C `long` or pointer is narrower than `jlong`.
Also, a few mishandlings of JNI local and global references were found, which would be latent problems on any architecture, but only surfaced on 32-bit, probably because of higher memory pressure. It is good to have those fixed for all architectures.
This episode underscores how very helpful it would be to get CI going for this project, with test builds for a range of architectures. Short of that, it also …
> Fix runtime errors caught on i386 builds

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/Lexicals.java
- pljava-api/src/test/java/LexicalsTest.java
Flesh out support for identifiers, unqualified and schema-qualified, for normal names and operator names. Also some support for recognizing SQL newlines and comments.
The obvious remaining omissions are character string and binary string literals. Those are important, but there are lots of uses for identifiers throughout PL/Java, so it seems worth pulling what is here now, and returning to the string literals another time.
> Add more constructs to the Lexicals class

- pljava-api/src/main/java/module-info.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/MetaDataInts.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/MetaDataTest.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/UsingProperties.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Parameters.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SPIActions.java
- pljava/src/main/java/org/postgresql/pljava/elog/ELogHandler.java
- pljava/src/main/java/org/postgresql/pljava/internal/Function.java
- pljava/src/main/java/org/postgresql/pljava/internal/ObjectPoolImpl.java
- pljava/src/main/java/org/postgresql/pljava/internal/Privilege.java
- pljava/src/main/java/org/postgresql/pljava/internal/Session.java
- pljava/src/main/java/org/postgresql/pljava/internal/TransactionalMap.java
- pljava/src/main/java/org/postgresql/pljava/internal/UncheckedException.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/AbstractResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/ObjectResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/ResultSetField.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIDatabaseMetaData.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIPreparedStatement.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIStatement.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SingleRowWriter.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SyntheticResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/TriggerResultSet.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/TypeBridge.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/Loader.java
- pom.xml
What a riot: the `nar-maven-plugin` goads `gcc` into flooding the output with every least interesting warning it's got, while at the same time the `maven-compiler-plugin` has been telling `javac` all along, by default, to report _no warnings at all_.
Override that default, and chase down a bunch of warnings thoughout the code that have not been visible in normal builds.
> Stop Maven's suppression of javac warnings

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/TypeOid.c
- pljava-so/src/main/include/pljava/Function.h
- pljava/src/main/java/org/postgresql/pljava/internal/Function.java
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/TypeOid.java
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
- src/site/markdown/examples/examples.md.vm
- src/site/markdown/examples/saxon.md
- src/site/markdown/use/use.md
- src/site/markdown/use/variables.md
PL/Java has been without one long enough. This start does not include much of an effort to improve or beautify the existing error messages for unsuccessful function definitions, but only to make the same old ugly ones happen at a more useful time, that of `CREATE FUNCTION` instead of only later with attempts to use the function.
Requires reworking some documentation, which formerly suggested installing example jars in an order that won't work if dependencies are being checked. Can either do things in the other order, or `SET check_function_bodies TO off` and go ahead without concern for ordering.
> Add validator function

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRWriter.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/Lexicals.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ComplexScalar.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ComplexTuple.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/IntWithMod.java
It was never satisfying to define a UDT in Java through annotations and still have the DDR generator not know that they need to be emitted before functions that use them, or after functions used in their definition, etc. It was easy enough (if tedious) to work around by adding explicit `provides`/`requires` annotations, but the DDR generator had all the necessary information to figure that out without such manual help. Now it does so, eliminating the tedium illustrated in jcflack/pljava-udt-type-extension@225ef5c.
Unlike pull request #159, which only needed to match Java types in order to improve the generator's ability to map types without explicit help, this follow-on work requires recognizing SQL types, and therefore needed considerably more infrastructure to model SQL identifiers and …
> Improve DDR generator by recognizing implicit dependencies (types and functions that use them, etc.)

- pljava-examples/pom.xml
- pljava-examples/src/main/java/org/postgresql/pljava/example/saxon/S9.java
Probably the most significant of the [changes in Saxon 10][chgs] for PostgreSQL's purposes will be that the XQuery [higher-order function feature][hof] is now included in the freely-licensed Saxon-HE, so that it is now possible without cost to have an XQuery 3.1 implementation that is lacking only the [schema-aware feature][saf] and the [typed data feature][tdf] (for those, the paid Saxon-EE product is needed), and the [static typing feature][stf] (which is not in any Saxon edition).
To compensate for delivering the higher-order function support in -HE, some optimizations have been moved to -EE. This seems a justifiable trade, as it is better for development purposes to have the more complete implementation of the language, leaving better optimization to be bought if and when needed. …
> Update Saxon-based examples to use Saxon 10

- pljava/src/main/java/org/postgresql/pljava/internal/DualState.java
After the auto-run examples in `pljava-examples`, an object histogram taken with `jhsdb` shows garbage-collectible instances of `PinCount` in third place, tens of megabytes worth. Tweak the implementation to keep a couple instances around and reuse them, a simple change that drops that class to an insignificant rank in the histogram.
The `DualState` statistics MBean shows that contention is very rare, a few contended pins for 10^4 constructed instances. Therefore, don't outfit every instance with a wait queue at construction time; let it be inflated the first time waiting is needed.
> Optimize DualState pinning/locking somewhat

- pljava-so/pom.xml
- src/site/markdown/build/versions.md
For Maven2Eclipse to know what to do with the various goals of a plugin, it was once necessary to have a `pluginManagement` section like the long one removed here. In M2E 1.1, it became possible for the plugin authors to include that information in the jar of a plugin. That is already done by the `nar-maven-plugin` and the `properties-maven-plugin` (at version 1.0.0, to which it is upgraded here). That leaves only the `maven-antrun-plugin` needing special treatment.
M2E 1.7 introduced a much less obtrusive form of special treatment, needing only the `<?m2e ignore?>` processing instruction added here.
However (nothing is ever simple), that requires declaring Maven 3.5.2 the minimum needed to build the project. Processing instructions made earlier versions crash ([MNG-6280][]).
So this …
> Simplify the Eclipse-specific stuff in pom.xml

- src/site/markdown/build/versions.md
As reported in #207, owing to incompatible later versions of plugins we haven't pinned, Mavens as old as 3.0.5 or so are no longer usable.
As of today, 3.2.5 will still complete a build starting with an empty repository, and 3.2.5 is as old as anyone should need; it will run on Java 6.
The larger issue that we should be more systematic about pinning dependency versions has merit, but it's, well, a larger issue.
> Update doc of oldest usable Maven version for 1.5 branch

- pljava-so/src/main/c/VarlenaWrapper.c
- pljava-so/src/main/c/type/TupleTable.c
Not very many this time around.
`SPITupleTable` sprouts a documented `numvals` field (postgres/postgres@bc8393c)
`tuptoaster.h` becomes `detoast.h` (postgres/postgres@8b94dab)
`heap_tuple_fetch_attr` gets non-heap-specific name `detoast_external_attr` (postgres/postgres@2e8b6bf)
> The minimal changes to build on PG 13beta1

- pljava/src/main/java/org/postgresql/pljava/internal/DualState.java
Applying the parts that make fewer garbage `PinCount` objects, but not the inflatable wait queue (which would be messy without Java 9 `VarHandle`s).
> Back-apply part of the inflatable-DualState patch to 1.5

- pljava-api/pom.xml
- pljava-examples/pom.xml
- pljava/pom.xml
- pom.xml
- src/site/site.xml
Deal with an assortment of Maven plugin passing wrong options to javadoc, newer Java bytecodes requiring newer BCEL and cascading updates to other Maven plugin versions, and version-specific Javadoc and Oracle apidocs website issues.
Maven makes things seem easy a lot of the time, but when it doesn't, it _really_ doesn't.
> Fix several problems with doc site generation in master

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/Invocation.c
Caught (#274) after 15 years during setup of CI for Google Summer of Code 2020.
> Fix stored non-global-JNI-reference bug #274

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SetOfRecordTest.java
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/type/Boolean.c
- pljava-so/src/main/c/type/Double.c
- pljava-so/src/main/c/type/Float.c
- pljava-so/src/main/c/type/Integer.c
- pljava-so/src/main/c/type/Long.c
- pljava-so/src/main/c/type/Short.c
Change one test case that was triggering (what seems to be) an overly strict `-Xcheck:jni` error, but arguably isn't a real problem. It could be revisited: there is a systematic way to eliminate the issue, but more work.
Primitive coercers of Java boxed arrays were not deleting their local refs, accounting for the vast majority of local ref capacity exceeded warnings. (Possible future optimization: have them use `PushLocalFrame`/`PopLocalFrame` at intervals, rather than deleting every local ref at retail.)
The rest of the messages were local ref capacity exceeded from internal Java code in the Java Management Extensions. No way to fix those in PL/Java, but because those warnings go through the `vfprintf` hook, that hook now contains a small state machine to recognize and suppress them. …
> Chase down issues reported by -Xcheck:jni

- pljava/src/main/java/org/postgresql/pljava/internal/Checked.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/XMLEventToStreamConsumer.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/Loader.java
`XMLEventToStreamConsumer` even had a comment saying "Do the below with lambdas once Java back horizon >= 8" and (probably because of the words between Java and 8) `grep` missed it in the earlier rounds of java8ification.
It would be trivial but for the fact that `n -> add(n)` could throw `XMLStreamException`, while an `Iterator`'s `forEachRemaining` doesn't accept a lambda that can throw anything. Happily, that's the kind of infelicity that `Checked` was meant to smooth over.
It turns out the initial commit of `Checked` had narrowly missed a much more pleasing way to set up the idiom. Now it's just
```
use(lambda that could throw stuff).in(code wanting lambda that can't)
```
as in this case
```java
use((Namespace n) -> add(n))
.in(event.getNamespaces()::forEachRemaining)
```
Conforming …
> Give Checked a nicer idiom, java8ify more

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SetOfRecordTest.java
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/Invocation.c
- pljava-so/src/main/c/type/Boolean.c
- pljava-so/src/main/c/type/Double.c
- pljava-so/src/main/c/type/Float.c
- pljava-so/src/main/c/type/Integer.c
- pljava-so/src/main/c/type/Long.c
- pljava-so/src/main/c/type/Short.c
The changes pulled to `master` from `chore/master/checkjni` in PR #276 should be applied here too.
The issues with JNI usage are bugs, and the filter on logging is important for spotting bugs (as the logging otherwise gets spammed with warnings from internal Java JMX code we're powerless to fix).
> Backpatch to REL1_5_STABLE the checkjni changes to master

- pljava-so/src/main/c/PgSavepoint.c
There were two issues here. That the prototype and function had the parameters in a different order was not a compile error (because the types were the same), but certainly misleading and a risk for future maintenance.
That the types were `int` in the prototype and `jint` in the function is a compile error, but has never been flagged by any compiler until building with Mingw-w64 (where presumably there is more of a distinction between `jint` and `int`).
Addresses #282.
Was introduced in 1.5.3 so should be backpatched to 1.5.
> Fix second bug found by GSoC 2020

- pljava-api/src/main/java/org/postgresql/pljava/Adjusting.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava/src/main/java/org/postgresql/pljava/internal/VarlenaWrapper.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
- src/site/markdown/use/sqlxml.md
At its introduction, this API only allowed adjustment to the handful of parser settings to be defaulted to restrictive values as recommended in the [OWASP cheat sheet][cheat].
However, there are several additional properties defined in recent Java releases for fine control of resource limits during parsing and individual protocols for accessing external resources. They are described in the [Java API for XML Processing (JAXP) Security Guide][jaxps]; make those also controllable through the `Adjusting` API.
Finally, SAX and DOM parsers can make use of an application-supplied `EntityResolver` or `Schema`, but the opportunity for setting each of those, for at least one type of parser, is hidden beneath the `SQLXML` API. Provide `Adjusting` methods for those too.
[cheat]: …
> Further develop the Adjusting.XML API

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/c/PgSavepoint.c
- pljava-so/src/main/c/SPI.c
- pljava-so/src/main/c/VarlenaWrapper.c
- pljava-so/src/main/c/type/Oid.c
- pljava-so/src/main/c/type/SQLXMLImpl.c
- pljava-so/src/main/c/type/TriggerData.c
- pljava-so/src/main/include/pljava/Function.h
- pljava-so/src/main/include/pljava/InstallHelper.h
- pljava-so/src/main/include/pljava/type/Portal.h
With the build process now using PostgreSQL's `CFLAGS` from `pg_config` and therefore being somewhat reasonable in the warnings it reports, the time seems right to fix some of them.
> Clean lint reported by compilers in CI runs

- pom.xml
Continuing in the vein of the recent updates in 6fabe39.
3.1.0 reduces the volume of the overwhelming useless stack
traces described in https://issues.apache.org/jira/browse/MPIR-373
> Update maven-project-info-reports to 3.1.0

- .travis.yml
- appveyor.yml
- pljava-packaging/src/main/java/Node.java
Commit 4e001ae added a similar feature in `Backend.c` for filtering messages to standard error, and there the less-jargon-y term _state machine_ was used, so for consistency, use that term in `Node.java` also. Anyway, because its states can be arbitrary lambdas, it doesn't have to be strictly a DFA; it would be simple to implement a pushdown automaton, for example (or just call another `stateMachine` from a state). It is easy to foresee tests that might do such things (to check a sequence of results by descending into the individual `ResultSet`s and into individual rows of those, for example). So `stateMachine` is just a better name.
This is the best time to change it, before it has appeared in a release.
> Second thoughts on naming new method 'dfa'

- pljava-so/pom.xml
- pljava-so/src/main/c/Backend.c
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
In some circumstances, `pg_config` can report a `CC` value that includes flags. For example, a vanilla build of PostgreSQL 12 in my Linux environment results in `gcc -std=gnu99` as the value of `CC`. So it seems it has to be treated as a list, with its first element used as the executable, and any others as arguments.
In the same PR, a couple cleanups that are not bugs, but quieting of messages showing up in CI builds.
> One bug in new compile/link code, and a couple of cleanups

- pljava-so/src/main/c/type/Timestamp.c
In 10.2, `session_timezone` gained a `PGDLLIMPORT` marking, making the workaround unnecessary. This typo'd conditional caused it to be used in later 10.x versions anyway.
It may be tempting to blame the change in `PG_VERSION_NUM` format with PG 10 (in 958fe54), but the value here was wrong for the old format too.
Addresses #297. Apparently the workaround wasn't reliable for all cases; as 10.2 has been out for 2½ years, there is probably no need to delve further into why.
> Avoid MSVC TZ workaround in PG 10.2 and later

- pljava/src/main/java/org/postgresql/pljava/internal/Checked.java
- pljava/src/test/java/CheckedTest.java
`Checked` contains versions and analogues of Java API functional interfaces, allowing checked exceptions where the Java versions don't, to simplify use of checked-exception-heavy APIs (JDBC or JAXP, anyone?) with Java's newer functional and stream APIs.
Here the set of To*prim*Function interfaces is expanded to cover all the Java primitive types, and all of them can participate in the `use(...).in(...)` idiom. An `AutoCloseable` with parameterized exception type is provided, along with Python-inspired `closing(...)` methods. New `Optional`s now cover all the primitive types.
> Continued development of the Checked* classes

- pljava-so/src/main/c/Function.c
... introduced in cdea77f, using `CallStaticObjectMethod` on a method that returns `void`. Hotspot's `-Xcheck:jni` never complained, but OpenJ9's catches it, and unless given as `-Xcheck:jni:nonfatal`, OpenJ9's will abort the process, reported as a `SIGSEGV`, making it perhaps more alarming than it needed to be.
As in Hotspot, OpenJ9's `-Xcheck:jni` messages are delivered through the `my_vfprintf` hook in `Backend.c`, and the problem is most easily found by setting a breakpoint there, then following a stack trace back to the offending call. The location reported _in_ the message is less useful, as it may just be the most recent native method call on the stack, which could be several calls above where the trouble is.
> Fix one JNI method-type mismatch

- .travis.yml
- .travis/travis_install_postgresql.sh
The `language: java` runner environment isn't able to install the same selection of JDKs on ppc64le as on amd64, so switch instead to the `language: minimal` runner, and explicitly get Java from adoptopenjdk.
That can be done with the `install-jdk.sh` script, which already exists in `/usr/local/bin` on and amd64 linux runner ... but not on ppc64le (or osx, for that matter). So, get that script from GitHub (at a specific SHA after reviewing it) when it isn't already installed. (It might be just as well to download it unconditionally, and never wonder what version the runner has.)
The `install-jdk.sh` script needs a patch to compute the right `JAVA_HOME` value on osx.
In constructing the URL for downloading from adoptopenjdk, the Travis arch value 'amd64' must be 'x64', and the Travis OS …
> Add builds for linux-ppc64le to the Travis-CI configuration

- pljava-packaging/build.xml
- pljava-packaging/src/main/resources/pljava--unpackaged--.sql
- pljava-packaging/src/main/resources/pljava--unpackaged.sql
- pljava-so/src/main/c/Backend.c
PostgreSQL 13 drops support for `CREATE EXTENSION ... FROM unpackaged`, on the rationale that any sensible site has already updated old unpackaged extensions to their extension versions. For PL/Java, though, there is still a realistic scenario where it ends up installed as 'unpackaged': if a `CREATE EXTENSION` failed because a setting needed adjustment, the admin supplied the right setting, and the installation then succeeded. That leaves PL/Java installed, but not as a packaged extension. The old `CREATE EXTENSION ... FROM unpackaged` syntax was the perfect recovery method for that. It will still work in PG versions < 13.
For PostgreSQL 13, recovery now requires two steps instead. The first step is `CREATE EXTENSION pljava VERSION unpackaged`, which will simply confirm the unpackaged …
> PG13 drops CREATE EXTENSION ... FROM unpackaged

- pljava-pgxs/src/main/java/org/postgresql/pljava/pgxs/ScriptingMojo.java
- pljava-so/pom.xml
- src/site/markdown/build/debugopt.md
`so.debug` is supported now and can be used just as with the earlier nar maven build process. `so.optimize` is currently not supported and a warning is displayed if the option is used.
> Add checks for so.debug and so.optimize in pljava-so build process

- pljava-examples/src/main/java/org/postgresql/pljava/example/jdk7/TypeRoundTripper.java
- pljava-so/src/main/c/Exception.c
- pljava-so/src/main/c/type/Array.c
- pljava-so/src/main/c/type/Boolean.c
- pljava-so/src/main/c/type/Double.c
- pljava-so/src/main/c/type/Float.c
- pljava-so/src/main/c/type/Integer.c
- pljava-so/src/main/c/type/Long.c
- pljava-so/src/main/c/type/Short.c
- pljava-so/src/main/c/type/TupleDesc.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/include/pljava/JNICalls.h
- pljava/src/main/java/org/postgresql/pljava/jdbc/SingleRowWriter.java
Issue #300 and a [pljava-dev thread][thd] identified some bugs in array handling. With these fixes:
* Arrays of primitive type can be retrieved from a `ResultSet` using `getObject`, either passing no requested class (the boxed array type will be returned, supporting nulls), or passing either the boxed array or primitive array class to the JDBC 4.1 `getObject` with a `Class` parameter, and getting that array type back (with any nulls mapped to zero/false for the primitive array type).
* Arrays of primitive or boxed primitive types can be passed to `updateObject` for columns of appropriate SQL types. Nulls in the boxed array type are handled.
* Value corruption in `updateObject(Byte[])` to an SQL `"char"[]` is resolved.
Regression tests are added for the above.
No work has been done on …
> Fix some bugs (but not lack of multi-dimension support) in array handling

- pljava-so/src/main/c/HashMap.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/include/pljava/HashMap.h
- pljava-so/src/main/include/pljava/HashMap_priv.h
`Type_fromJavaType` can create a `Type` on the fly if it is for an array. It is possible for one Java array type to be associated with more than just one PostgreSQL type (for example, Java `Object[]` for an array of pretty much anything, `String[]` and types that can be rendered to text, and more obscure cases like `byte[]` being associated with `"char"[]` as well as `bytea`).
That led to order-dependent failures when the `s_obtainerByJavaName` cache was keyed only by Java name. Key it now by name+oid, but (to limit the intrusiveness of the patch), use `InvalidOid` in the key except when caching and looking up types that correspond to Java arrays.
This C-based type hierarchy implementation has grown to what is probably its ultimate height and wobbliness (to say nothing of how one would …
> Key s_obtainerByJavaName by name+oid for arrays

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Function.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/AnyTest.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Variadic.java
As it was discovered in 6745166 that PostgreSQL already will do most of the lifting needed to make variadic PL/Java functions work, and in c198a5e that the remaining blocking bug was fixed, add here a `variadic` element for the `@Function` annotation, teach the SQL generator the right output to produce for it, and add a new example demonstrating the feature.
> Support variadic functions

- pljava-examples/src/main/java/org/postgresql/pljava/example/UsingProperties.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/UsingProperties.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/saxon/S9.java
Not necessarily the ones most likely to need 64-bit row counts (at the moment, I think even Saxon has an internal limitation to 32-bit sequence lengths), but these are trivial to update, and at least serve to illustrate use of the interface.
> Migrate a few examples to ResultSetProvider.Large

- pljava-packaging/src/main/resources/pljava.policy
- pljava-so/src/main/c/type/String.c
- pljava/src/main/java/module-info.java
- pljava/src/main/java/org/postgresql/pljava/internal/SQL_ASCII.java
- pljava/src/test/java/CharsetTest.java
- pom.xml
- src/site/markdown/use/charsets.md
- src/site/markdown/use/variables.md
PostgreSQL's legacy `SQL_ASCII` encoding is difficult to use in Java because 128 of its code points have no defined mapping to Unicode, which Java uses. Add a Java `Charset` supporting the encoding names `X-PGSQL_ASCII` or `SQL_ASCII`, which maps the ASCII characters as expected, and reversibly encodes the others using Unicode permanently-undefined codepoints; Java code can then use assorted `String` methods, regular expressions, etc., which will generally match in the ASCII regions and, with some care, leave the non-ASCII parts unmolested.
> Add an SQL_ASCII encoder/decoder

- .travis.yml
- appveyor.yml
- pljava-api/src/main/java/org/postgresql/pljava/annotation/Cast.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLAction.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLActions.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-api/src/test/java/LexicalsTest.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ConditionalDDR.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Enumeration.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/IntWithMod.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/JDBC42_21.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PreJSR310.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/RecordParameterDefaults.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SPIActions.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Triggers.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/UnicodeRoundTripTest.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/XMLRenderedTypes.java
Recent work on the SQL generator added enough implicit-dependency-tracking infrastructure that it is now fairly straightforward to implement a `@Cast` annotation (and possibly others in the future, such as for aggregates and operators).
Effect of this patch can be seen in further simplification of Bear Giles's UDT example in jcflack/pljava-udt-type-extension@7987f29.
Until now, the only (ersatz) "repeatable" annotation was `@SQLAction`, which appeared in PL/Java 1.5 supporting Java earlier than 8, so in order to 'repeat' it, it had to be wrapped inside `@SQLActions`.
As PL/Java 1.6 supports only Java versions with real repeatable annotations, also declare `SQLAction` to be officially repeatable. That allows it to be used without wrapping in `@SQLActions` (though old code that does wrap it …
> Teach the SQL generator to declare PostgreSQL casts

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/UsingProperties.java
- pljava-packaging/src/main/resources/pljava.policy
- pljava/src/main/java/org/postgresql/pljava/sqlj/Loader.java
PL/Java's class loader has historically handled resource lookups by returning a URL that has a custom `URLStreamHandler` wired in. Permission to do that wasn't included in the `pljava.policy` shipped with 1.6.0. Fix that. Addresses #322.
Still does not get closer to fixing #266, but at least avoids making it worse.
> Fix access-denied exceptions from getResource or ResourceBundle.getBundle

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Function.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ReturnComposite.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/UsingProperties.java
Follows a fortuitous discovery that zero changes are needed to PL/Java's runtime code for functions with `OUT` parameters to work—they are simply treated the same as any other `RECORD`-returning function, with a writable `ResultSet` added as a last Java parameter. It's even possible somebody already knew that, but there were no existing examples showing it, and it was a discovery to me.
With the small addition of an `out` element to the `Function` annotation, poof! Generated SQL for PL/Java functions with `OUT` parameters.
It is a useful option. Functions could already be declared as returning `RECORD`, but then every SQL query using them has to supply `AS (`_column definition list_`)` after the function call. They could already be declared to return some known composite type, but that …
> Allow declaring functions with OUT parameters

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Aggregate.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Aggregates.java
A new `@Aggregate` annotation allows generating PostgreSQL `CREATE AGGREGATE` with most of the bells and whistles (including some that there is not yet any way for pure PL/Java functions to implement). Omitted for the moment are `SERIALFUNC` and `DESERIALFUNC` (there isn't much PL/Java functions can do with datatype `internal`), and `SORTOP` (not enough awareness of operators yet). There is still `@SQLAction` for any rare need to get a `CREATE AGGREGATE` into a deployment descriptor if this annotation can't describe it.
> Add SQL generation for user-defined aggregate functions

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Aggregate.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/BaseUDT.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/MappedUDT.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/Operator.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/Trigger.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ComplexScalar.java
- pljava/src/main/java/org/postgresql/pljava/internal/Function.java
A new `@Operator` annotation allows PostgreSQL `CREATE OPERATOR` to be generated, with compile-time sanity checking, and concise notation when the annotation is on a Java method, from which many of the operator's vitals can be inferred.
The generator can emit synthetic function and operator declarations to complete a set of operators related to each other by commutation and/or negation, relieving much of the tedium of implementing a full set of `btree` relational operators, for example, or a set of cross-type operators and their commutators.
This PR does not add generation of operator classes or families. Until that is added, `CREATE OPERATOR CLASS` and friends can be done in `@SQLAction` blocks, declaring `requires` on some tag the needed operators/functions will 'provide', to get the …
> Add SQL generation for user-defined operators

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pom.xml
Revert the unsatisfying workaround added in c763cee for javac 10 and 11 misbehaving when passed a `--release` naming an earlier release, and add a better workaround in `DDRProcessor` itself. Now it is possible to build for `--release 9` whichever toolchain version is used for the build, and that was the original intent and so is much more satisfying.
It turned out (unsurprisingly, in retrospect) that the same issue would also bite someone building user code, and to have no better answer than "fudge your target release if building with 10 or 11" would be hard to stomach.
Addresses #328.
> Better workaround for javac 10 and 11 issue

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ComplexScalar.java
and, in passing, a lint warning that came in with the Aggregate annotation stuff.
> Fix a bug that survived into the recent Operator annotation PR

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
My usual advice to anyone considering XSLT 1.0 is "run away!" because it is so primitive and limiting compared to the later versions. And certainly what's possible by downloading Saxon and using XSLT 3 or XQuery 3.1 is far and away preferable to struggling with XSLT 1.0.
Its one advantage is that it is directly included in Java with no need of a large, separately-downloaded jar, and that's enough to make it useful if there's some simple transformation to be done that doesn't require the big guns. Another redeeming feature of Java's XSLT support is that it can call out to Java methods, often allowing a way around the otherwise crippling limitations of strict XSLT 1.0.
So, it is worthwhile to take the existing example methods demonstrating the XSLT 1.0 support and give them a little further …
> Flesh out the XSLT 1.0 functions in the XML examples

- .travis.yml
- appveyor.yml
- pljava-packaging/src/main/resources/pljava.policy
- pljava-so/src/main/c/Backend.c
- pljava/src/main/java/module-info.java
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pljava/src/main/java/org/postgresql/pljava/internal/TrialPolicy.java
- pljava/src/main/java/org/postgresql/pljava/policy/TrialPolicy.java
- pljava/src/main/java/org/postgresql/pljava/policy/package-info.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/Handler.java
- src/site/markdown/use/policy.md
- src/site/markdown/use/trial.md
- src/site/markdown/use/use.md
Issue #331 prevents extension startup by a normal (non-superuser, non-`pg_read_all_settings`) user. Fix that.
Further, by request, make available a custom security policy that can log permission requests that the regular policy would deny, but then allow them, so that existing code being migrated from PL/Java 1.5 can be run without disruption while evaluating it for permission grants that may need to be added to the regular policy.
It works like this: `pljava.policy_urls` point to the normal policy file(s), as usual. That's where the ultimate policy for production will be developed.
You can create another policy file somewhere, the "trial" policy, and point to it with `-Dorg.postgresql.pljava.policy.trial=`_url_ added to `pljava.vmoptions`. Anything _this_ policy allows will be allowed, …
> Fix a failure to start as normal user, and make a custom security policy available for migrating from 1.5

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/type/Type.c
Travis builds against Linux PG13 were showing gcc invoked with `-Wimplicit-fallthrough=3`, so quiet the warnings that result. I cannot explain why gcc is not respecting the `pg_unreachable` built into `elog(ERROR` but does respect a `pg_unreachable` added right there in the code.
> Quiet new gcc implicit-fallthrough warnings, and some minor Java lint

- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
The addition of a new function in the `sqlj` schema should have occasioned a new `SchemaVariant` in `InstallHelper` that would make sure the same function gets installed during an update from an earlier installed version. That was overlooked.
Addresses #341.
> Install 1.6.0's new sqlj.alias_java_language function when updating

- pljava-api/src/main/java/org/postgresql/pljava/annotation/SQLType.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
Because Java disallows `null` as an annotation element value, it has never been possible to say `defaultValue=null` for a method parameter. Allow `optional=true` as an alternative meaning just that.
Use it to tweak the `PassXML.transformXML` example function so it doesn't set indent-related properties on the transformer unless the caller specified them explicitly.
> Give SQLType an optional= element

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ComplexScalar.java
With the bug fixed, it is now possible to write one Java method, say `boolean eqToReal(Complex,double)`, and synthesize from it the four operators `=(Complex,double)`, `<>(Complex,double)`, `=(double,Complex)`, and `<>(double,Complex)`.
The runtime was already up to the job, but the SQL generator couldn't figure out the declarations.
> Fix a bug that blocked SQL generation for some synthetic operator derivations

- pljava-pgxs/src/main/java/org/postgresql/pljava/pgxs/AbstractPGXS.java
- pljava-pgxs/src/test/java/PgConfigPropertyAsListTest.java
The change in f8e475b was a hasty measure on discovering that the single quotes in a quoted argument reported by `pg_config` may appear within the argument rather than only surrounding it. It solved that problem, but can be fooled into empty arguments where multiple spaces separate arguments in the `pg_config` output (issue #347).
Revert to the regex-based approach from before f8e475b and just tweak that.
This implementation openly makes _no_ allowance for an argument having a single quote in its content. PostgreSQL's own build process failed in a simple attempt to create such a case, so supporting it here is probably not necessary for now.
> Do not turn consecutive spaces in pg_config output into empty cc/ld arguments

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PreJSR310.java
- pljava-so/src/main/c/JNICalls.c
- pljava/src/main/java/org/postgresql/pljava/internal/EntryPoints.java
- pljava/src/main/java/org/postgresql/pljava/internal/Function.java
- src/site/markdown/use/policy.md
When a PL/Java function is called, it gets its own access control context selected based on the "procedural language" and trusted/untrusted attribute; it is simple to grant it whatever permissions it may need in the policy file.
At `CREATE FUNCTION` time, when validating (`check_function_bodies` is `on`), run the class initializer the same way. That avoids the inconvenience reported in #342, where permissions needed only by the user class (used in its static initializer) had to be granted also to PL/Java itself or the `CREATE FUNCTION` would fail validation, because some PL/Java code was still on the protection domain stack when the initializer was invoked.
Add a section on the topic to `policy.md`.
> When validating, run class initializer in same access control context as when function is called

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/include/pljava/InstallHelper.h
Addressing #350:
* Don't segfault after reporting a failure to find the expected first Java class
* Don't have backend exit with no log message if the JVM can't build the boot module layer
* Do emit a very early `DEBUG2` message with version info for the shared object, just to allay suspicions about mismatched versions.
> Improvements to experience when pljava.module_path may not be right

- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/include/pljava/InstallHelper.h
PL/Java can be invoked in an autovacuum worker process if there is a functional index declared that uses a PL/Java function. Like the background worker case, there may not be a `MyProcPort` structure available.
This fix is only usable back to PG 9.5. In older PG versions, it may be necessary to use `false` as the per-table `autovacuum_enabled` storage parameter on any table having a Java-based functional index, and run explicit `VACUUM` on such tables over a normal connection. Prior to PG 8.4, there was no such per-table setting, and the only workaround would be to forego autovacuum database-wide and use explicit `VACUUM` on some schedule.
> Treat an autovacuum worker process specially

- pljava-so/src/main/c/type/String.c
- pljava/src/main/java/org/postgresql/pljava/internal/Backend.java
- pljava/src/main/java/org/postgresql/pljava/internal/SQL_ASCII.java
- pljava/src/main/resources/META-INF/services/java.nio.charset.spi.CharsetProvider
- src/site/markdown/use/charsets.md
- src/site/markdown/use/variables.md
1.5's handling of the `SQL_ASCII` encoding was a bit worse than just "it's a Unicode-incompatible PostgreSQL encoding, good luck with it"; issue #340 identified an actual live bug. (`pg_do_encoding_conversion` can be passed a non-NUL-terminated string, and can return that string unchanged in some cases, as a comment on it duly warns; it turns out that one such case is "every time, if your server encoding is `SQL_ASCII`".)
Knowing that the existing behavior is buggy weakens the argument against backporting the `SQL_ASCII` behavior change from 1.6. So here it is.
> Backport 1.6's handling of SQL_ASCII to 1.5

- pljava/src/main/java/org/postgresql/pljava/internal/Backend.java
- src/site/markdown/install/install.md.vm
PL/Java 1.5's build system already breaks as of Java 15, so it won't be necessary to add `SuppressWarnings("removal")` anywhere in the 1.5 sources. It also will not start by default on a JVM later than 17, because it does not use `-Djava.security.manager=allow` among the invocation options by default. The logic here is only to detect if it has been run with that option explicitly added (in `pljava.vmoptions`) and is running on a Java version where the functionality has been gutted.
More at https://github.com/tada/pljava/wiki/JEP-411
> Detect if running in a post-JEP411 JVM

- .github/workflows/ci-runnerpg.yml
- .travis.yml
- appveyor.yml
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/DualState.c
- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/c/JNICalls.c
- pljava-so/src/main/include/pljava/Backend.h
- pljava-so/src/main/include/pljava/JNICalls.h
- pljava/src/main/java/org/postgresql/pljava/internal/Backend.java
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pom.xml
The PL/Java 1.6 series definitely relies on the Java functionality that JEP 411 begins to phase out; it will take some future PL/Java major release to implement the security enforcement in some completely different way. But 1.6 will remain usable at least as long as Java 17 does, and Java 17 is positioned as a long term support release.
This pull request simply makes adjustments in 1.6 to provide useful advance notice of the future changes, and useful and specific exception messages if run on a later Java version with the needed functionality missing. (Late in the process, when some future Java version has completely removed the classes and methods in question, this PL/Java version will flat-out fail to start, with linkage errors. A future minor release could set out to address that by …
> Preparations in PL/Java 1.6 for impacts of Java's JEP 411

- pljava-so/src/main/c/type/Type.c
- src/site/markdown/develop/coercion.md
Check at runtime whether a `MappedUDT` is being applied to a PostgreSQL type declared with `typlen` of -2 (a variable-length, NUL-terminated representation), and report an error if so. Explain in the developer documentation why the implementation cannot support the use.
It already didn't work, but an explanatory error message is a better way of not working.
Addresses #370.
> Document and enforce MappedUDT/typlen-2 exclusion

- pljava-api/src/main/java/org/postgresql/pljava/annotation/BaseUDT.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
The PostgreSQL type 'category' is a bit awkward, because there are several predefined, but other codes can be used for custom purposes. So an enumeration of the predefined ones cannot be used as the type of the 'category' annotation element, but it still can improve readability when one of the predefined categories is what's wanted.
Also add a warning from the DDR processor if an upper-case category code has been given (that's the range reserved for PostgreSQL's predefined categories) but it doesn't correspond to any value of the `PredefinedCategory` enum.
> Expose predefined category codes in BaseUDT

- pljava-api/src/main/java/org/postgresql/pljava/annotation/Function.java
- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ReturnComposite.java
When generating a function declaration for a function with exactly one `OUT` parameter, the declaration must have the scalar form where `RETURNS` identifies the single parameter's own type instead of `RECORD`.
Discussion: https://www.postgresql.org/message-id/619BBE78.7040009%40anastigmatix.net
Added more checks on co-appearance of `type=` and `out=` and a way to use `@SQLType` to disambiguate in cases where the method "shape" would fit a composite-returning method or an ordinary method with a row-typed trailing input parameter.
In cases where PL/Java has relied on an assumption in generating a function's declaration (some of the assumptions have long standing in PL/Java history), it still proceeds silently at compile time, but generates a comment into the deployment descriptor …
> Emit correct SQL declaration for one OUT parameter

- pljava-api/src/main/java/org/postgresql/pljava/BasePrincipal.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/Lexicals.java
Clarified comments in `sqlgen.Lexicals`, and a missing `equals()` short-circuit in `BasePrincipal`, and making its name field protected rather than private.
> A few nits noticed after 1.6.3

- pljava-api/src/main/java/org/postgresql/pljava/Session.java
- pljava/src/main/java/org/postgresql/pljava/internal/Backend.java
- pljava/src/main/java/org/postgresql/pljava/internal/Session.java
- pljava/src/main/java/org/postgresql/pljava/internal/SubXactListener.java
- pljava/src/main/java/org/postgresql/pljava/internal/XactListener.java
0772030 inadvertently created a chance for the user code to retrieve one `Session` instance from `SessionManager.current()` while implementation code gets a different one from `Backend.getSession()`.
In passing, fix a typo in the Session API interface's javadocs.
Addresses #388.
> Avoid Session split-brain syndrome

- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/type/Type.c
The clever arrangements in `Function_vpcInvoke` to avoid duplicating the context classloader assignment on the first call were too clever by half, because every call to `vpcInvoke` will have come through `Function_invoke`, which already assigned it, and therefore the duplicate assignment was still happening on every call but the first.
Addresses #389.
> Fix a thinko in context classloader management

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/JDBC42_21.java
- pljava-so/src/main/c/type/Date.c
- pljava-so/src/main/c/type/Time.c
- src/site/markdown/use/datetime.md
The (documented, but not necessary) limitation in the mapping of `date` infinity/-infinity to java.time.LocalDate was an avoidable integer overflow. It only affected dates within 30 years of `infinity` or `-infinity`.
Addresses #390.
In passing, solve the problem that the valid PostgreSQL `time` value 24:00:00.000000 is not valid to `java.time.LocalTime` or `OffsetTime`. The Java classes will accept the preceding nanosecond, which is still distinguishable from any other mapped PostgreSQL value (as those have only microsecond resolution), so make that the mapping of 24:00:00.
> Fix mapping errors to java.time dates and times

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
Because PL/Java must be compilable on any Java back to release 9, the `DDRProcessor` cannot refer by name to any `SourceVersion` enum constant later than `RELEASE_9`. It also, arguably, _should_ not, because its development and testing rely on the `javax.lang.model` API as of release 9.
Happily, in practice, later Java releases do not often break the `DDRProcessor` code, so user Java code for releases later than 9 can be compiled with no difficulty, other than a compiler warning about the processor's source version being pegged at 9. But the warning is an obstacle if the user code is being compiled with a fail-on-warning policy, as in issue #403.
This patch adopts a compromise position, and keeps track of the latest source version for which the annotation processor at least has been seen …
> Compute supported source version in DDRProcessor

- .github/workflows/ci-runnerpg.yml
- appveyor.yml
See issue #434.
In passing, also add semicolons where jshell is (sometimes) lax about them. It is sometimes handy to use copy/paste from these test scripts into a live jshell, and its tolerance of missing semicolons can be diminished then.
Refactoring the github and appveyor CI scripts to share one copy of the jshell script would be a fine thing.
> Disable failing CI test until an issue 434 fix

- pljava-so/src/main/c/type/String.c
- pljava-so/src/main/include/pljava/type/String.h
Addresses #410. In postgres/postgres@639a86e, the `Value` flavor of `Node` struct was retired, and `Integer`, `Float`, `String`, and `BitString` became `Node` structs in their own right; the name `String` collides with the one in PL/Java's `String.c`. An easy solution is to change the name of the latter.
Thanks to Francisco Miguel Biete Banon; tested by Christoph Berg, tayalrun1, Frank Blanning, aadrian, Yuril Rashkovskii.
The upstream change made changes in `nodeToString` in `outfuncs.c`, but only as needed to preserve the original `pg_node_tree` syntax, so no attention to `PgNodeTreeAsXML` is needed. (It would be good for that to have a regression test, on general principles.)
> Fix struct name collision caused by upstream PostgreSQL change

- .github/workflows/ci-runnerpg.yml
- appveyor.yml
... thanks to a tip from Rodrigo Alvarado a little tidier than what's on the wiki.postgresql.org Apt page.
And update the list of Java versions tested to cover more recent ones.
Also, for now, suppress the Appveyor tests that have been reliably falling over for some reason of their own.
> CI chore: fetch key for PGDG apt repository

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/OnInterface.java
- pljava/src/main/java/org/postgresql/pljava/internal/Function.java
The SQL/JRT standard has always just said class, but it's debatable whether it intended to mean 'class' strictly (and rule out SQL use of a static method on an interface), or simply used 'class' in a broader sense not excluding interfaces. As there is no technical obstacle to using static methods that have been supplied on an interface, relax the annotation-processing-time check that needlessly prevented that.
Add an example that tests that, and also the declaration of methods on nested classes and interfaces (as long as everything is `public` on the way).
Addresses https://github.com/tada/pljava/issues/426.
> Relax the check of a function's enclosing type

- .github/workflows/ci-runnerpg.yml
- appveyor.yml
- pljava-packaging/src/main/java/Node.java
- pljava-packaging/src/main/resources/pljava.policy
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
- pljava/src/main/java/org/postgresql/pljava/management/SQLDeploymentDescriptor.java
Fix some issues identified in #425 that kept `install_jar` from working with an http URL.
* `HttpURLConnection` has a `getPermission` method that is supposed to return the least permission needed to retrieve the resource. But it should be possible to use either a suitable `SocketPermission` or the newer `URLPermission`, and that old method only returns the first. If the policy grants a `URLPermission` and the permissions are intersected with the set containing just `SocketPermission`, an empty set results. Make sure the `URLPermission` is also included.
* Java does not automatically use authentication info in the URL if the server sends a password authentication challenge. An `Authenticator` instance that will do that has to be set on the `HttpURLConnection` first.
Update the GitHub …
> Support `install_jar` from an http URL

- src/site/markdown/install/vmoptions.md
- src/site/markdown/use/jpms.md
- src/site/markdown/use/use.md
- src/site/markdown/use/variables.md
PL/Java code loaded with `install_jar` is treated as unnamed-module, legacy classpath code. Such code is advertised as having access to all readable modules, without having to declare dependencies (as it can't declare dependencies; it would have to be a named module to do that).
Ah, but what are "all _readable_ modules"? Only the ones enumerated at JVM startup, using as root modules PL/Java itself and anything named with `--add-modules`. So that option must be used if any Java modules will be needed beyond the ones PL/Java itself depends on. PL/Java's documentation didn't explain this.
This added documentation addresses #419.
> Document the use of --add-modules

- .github/workflows/ci-runnerpg.yml
- appveyor.yml
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
PL/Java supports a pre-extension, legacy installation method just using the `LOAD` command. It can still have some uses, such as when a DBA does not have write access to the directories where official extension files have to go. And PL/Java has supported later packaging such an 'unpackaged' installation into extension form. (The old PostgreSQL syntax for that, `CREATE EXTENSION FROM unpackaged`, was dropped in PG 13, but an equivalent sequence of steps still works).
That packaging used to rely on `CREATE OR REPLACE` silently absorbing a preexisting object into the current extension. However, since postgres/postgres@b9b21ac, `CREATE OR REPLACE` instead fails if the object exists and is not yet an extension member. Therefore, the few objects for which PL/Java does `CREATE OR REPLACE` within …
> Restore "installed by `LOAD` then packaged as extension"

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/Lexicals.java
The Java bug [JDK-8309515][bug] first appears in Java 20, and has been quickly fixed for 21 (in openjdk/jdk@90027ff) and will presumably be backpatched to some update of 20.
Therefore, rather than bending over backward to include a workaround, simply include a test for the bug, with advice to use a working (pre-20, or recent, fixed) Java version.
Addresses #435.
[bug]: https://bugs.openjdk.org/browse/JDK-8309515
> Simply reject a Java version affected by JDK-8309515

- pljava-api/src/main/java/org/postgresql/pljava/Adjusting.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
Java 17 adds (and prominently documents in the `java.xml` module-info javadocs), new, standardized, easy-to-remember names for a dozen or so of the XML implementation-specific properties and features.
And the standardized names are ... different from the old ones.
More names to feed into `setFirstSupported{Feature,Property}` when trying to adjust things.
The naming headaches are now visible outside of just the implementation module, because there are new standardized names for a `Transformer` property and feature also, which are used in the XSLT example code in `PassXML`.
So this is a good time to factor a `setFirstSupported(...)` generic function out of the various copies buried in `SQLXMLImpl`, and expose it in the `Adjusting.XML` API so client code can use it too, and use it that way …
> Add Java 17 names for XML implementation props

- pljava-api/src/main/java/org/postgresql/pljava/annotation/package-info.java
- pljava/src/main/java/org/postgresql/pljava/internal/VarlenaWrapper.java
Discovered one that had been rendered rather incoherent by a later change to the code, and another still referring to a Java 1.6 requirement from a PL/Java version that requires Java 9.
> Fix bogus out-of-date Javadoc comments

- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
Instead of relying on obsolete attribute `valign` to match the parameters to their descriptions, give the tables the class "striped", which is described in the javadoc-supplied stylesheet.css as one of the "Styles for user-provided tables".
> Javadoc >= 17 rejects non-HTML5 attributes

- pljava-examples/pom.xml
- pljava/pom.xml
In older Java versions, it was necessary to pass along the initial javadoc arguments (the ones a file manager would care about) in a separate step before calling the tool. Starting in 19, that's not only no longer necessary, but fails with "--module-source-path specified more than once", so omit that step when building the javadoc on Java 19 or later.
> Skip `handleFirstOptions` for javadoc >= 19

- pljava-api/src/main/java/org/postgresql/pljava/sqlgen/Lexicals.java
- pljava-api/src/test/java/LexicalsTest.java
Supply a `NEWLINE` pattern in `sqlgen.Lexicals` that still meets the goal of relying on Java's regex engine for precisely what is or isn't a newline, but without the ill-thought-out sensitivity to the previous match result reported in issue #455.
> Improve `NEWLINE` pattern

- pljava-so/src/main/c/PgObject.c
- pljava-so/src/main/c/type/Type.c
- pljava-so/src/main/include/pljava/PgObject_priv.h
It is easy enough to stop casting `_PgObject_pureVirtualCalled` to incompatible function types, as it makes modern compilers suspicious, and was only done in three places anyway.
> Quiet warnings about casts of function types

- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/type/AclId.c
Accommodate upstream changes postgres/postgres@ca1e855, postgres/postgres@320f92b, and postgres/postgres@c727f51 to permit building on PG 16 (beta 3).
May keep this PR open until PG 16 GA, in case of any late-breaking changes.
> Support PostgreSQL 16

- .github/workflows/ci-runnerpg.yml
- appveyor.yml
- pljava-packaging/pom.xml
- pljava-packaging/src/main/java/Node.java
- pljava-packaging/src/site/markdown/index.md
- src/site/markdown/develop/node.md
The `PostgresNode`-like test harness Easter egg included in the package jar has until now only supported pgjdbc-ng (and had some notes in the documentation about issues with PGJDBC that may have been observed at one time, but that I cannot reproduce or vouch for now). So, make the necessary changes in `Node` so that either driver can be used, and fix the documentation accordingly.
> Let the `Node` test harness use either PGJDBC or pgjdbc-ng

- pljava/src/main/java/org/postgresql/pljava/internal/Portal.java
The `java_thread_pg_entry=allow` mode is the one longest supported in PL/Java, and it ought eventually to be phased out, as its way of serializing threads' access to PG is fussy, and involves quite unconvincing manipulation of PG internal variables used for detecting excessive stack use. A better mode, not yet implemented, would be to forever allow only the original PG thread to enter PG; on entry to PL/Java, it should dispatch the Java work quickly onto some other thread and then wait as a single-thread executor service to handle `doInPG` requests, until completion of the thread handling the work.
However, until that better mode is implemented, `allow` mode ought to be usable. Issue #471 identified a bug in `Portal.close` causing it to fail depending on the thread invoking it.
Although …
> Fix `Portal.close` for `java_thread_pg_entry=allow` mode

- pljava-so/pom.xml
- src/site/markdown/build/freebsd.md
Patch for building on FreeBSD supplied by Achilleas Mantzios in PR #475, rebased here and with the appropriate doc update in `build/freebsd.md`.
> Build on FreeBSD (PR #475 rebased)

- pom.xml
Change: update maven plugin versions to work with versions that don't suffer critical vulnerabilities
> Update maven plugins versions

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-pgxs/pom.xml
- pljava-so/src/main/c/Backend.c
- pom.xml
- src/site/markdown/use/policy.md
These changes take care of building and using PL/Java on Java 22.
A separate patch will address new Java 22 features that can be exposed in PL/Java's API for use by user code.
Naturally, no patch will begin using Java 22 features within PL/Java _itself_ until a future major release adopts a newer minimum build version.
> Changes to build/use PL/Java on Java 22

- pljava-api/src/main/java/org/postgresql/pljava/Adjusting.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
- src/site/markdown/use/sqlxml.md
Provide access for client code to features introduced in Java 22.
The Java 2 release notes include new XML features that should be exposed by PL/Java's `Adjusting.XML` API so they can be used by client code.
One new feature is already sufficiently exposed by the `setFirstSupportedProperty` method, so only a documentation note is added.
> Expose Java 22 features to PL/Java user code

- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
The logic that chooses wrapping `SQLException` subclass and `SQLstate` for XML parse exceptions and I/O exceptions in `XMLCopier.saxCopy` is now duplicated in `AdjustingDOMSource.get`, to eliminate the inconsistency that an XML parse error would be reported as a class 22 `SQLDataException` if using the SAX or StAX APIs, but as a class XX internal-error `SQLException` if using the DOM API.
Addresses issue #481.
This does change a user-visible behavior. It would be straightforward to make it depend on a flag, if there exists any code depending on the prior behavior. (I am judging that unlikely.)
> Consistent (SAX/DOM) wrapping of XML parse errors

- pljava-so/pom.xml
Addresses issue #485: anyone unlucky enough to build in an environment matching none of the probe methods for known platform rules would be faced with a JavaScript null-pointer exception instead of a message giving any clue where to look for the problem.
Adds a message explaining that no known platform rules matched, where to look in `pljava-so/pom.xml` to see why an already-supported platform might not have matched, or to add support for a new platform.
> Improve build output when no known platform rules matched

- .github/workflows/ci-runnerpg.yml
Per the 'roadmap' announced in actions/runner-images#9255, `macos-latest` now points to `macos-14` as of Q2, and the `macos-14` image does not supply any version of PostgreSQL (or any database; its much-shorter installed-software list might not be an oversight). Bad news for the quick workflow that relies on the runner's installed version.
Limit the MacOS CI to the `macos-12` runner for now. That should hold until the image is removed in Q4. A workflow that installs a specified PostgreSQL version may be needed after that.
Also, shorten the name of the workflow. It was too long to read in the online display of checks.
And add a restrictive `permissions:` entry, which was missing, and its absence is not secure-by-default.
> CI: macos-latest: now without PostgreSQL

- pljava-pgxs/pom.xml
- pljava-pgxs/src/main/java/org/postgresql/pljava/pgxs/AbstractPGXS.java
- pljava-pgxs/src/main/java/org/postgresql/pljava/pgxs/PGXSUtils.java
- pljava-pgxs/src/main/java/org/postgresql/pljava/pgxs/ReportScriptingMojo.java
- pljava-pgxs/src/main/java/org/postgresql/pljava/pgxs/ScriptingMojo.java
- pljava-so/pom.xml
Add to the build scripting for `pljava-so` so that the detailed `PG_VERSION_STR` will appear in the Maven output to clarify what PG version has been found to build against.
This should simplify responding to issues like #487, where the first obvious question is "what version of PostgreSQL is this being built against, anyway?".
The version is logged at Maven's `INFO` level, so should be present in the output with no special effort.
Also log, at Maven's `DEBUG` level, the actual arguments being supplied to the compiler and linker. These will only be seen if Maven is run with `-X`, which therefore can be useful if some more thorny build issue needs to be investigated.
Improve javadoc in `pljava-pgxs`, to serve as a better reference for what the functions and objects used in the `pljava-so` …
> Add output to simplify troubleshooting native build

- pljava-examples/pom.xml
- pljava-packaging/pom.xml
- pljava-pgxs/pom.xml
- pljava/pom.xml
Recent versions of `javac` warn that annotation processing might not happen in the future unless `--processor`, `--processor-path`, `--processor-module-path`, or some `-proc` option is explicitly given. Nothing was going to break, because the POMs where annotation processing needs to happen already set `--processor-module-path`. But that doesn't silence the warning. Only an explicit `-proc:full` or `-processor org.postgresql.pljava.annotation.processing.DDRProcessor` accomplishes that. Because `-proc:full` is unrecognized before Java 21, but the longwinded `-processor` spec works in all supported versions, the longwinded form is used here (even though it seems a complete waste of the elegance of the original processor discovery scheme).
Warnings were also appearing in a couple of …
> Hush recent javac annotation-processor warnings

- pljava-so/src/main/c/InstallHelper.c
- pljava-so/src/main/c/PgSavepoint.c
Slight rework of PR #501 from @fmbiete, who found the new names of `AmBackgroundWorkerProcess` and `AmAutoVacuumWorkerProcess`, and the demise of `SPI_restore_connection`, to be the only changes needing attention. 
A review of the PG17 release notes suggests the no-longer-NUL-terminated input to UDT `receive` functions as the only other change likely to matter, but by inspection, existing code already relies on the count and not the NUL.
Addresses #499.
> Support PostgreSQL 17

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-so/src/main/c/Backend.c
- src/site/markdown/use/policy.md
These changes take care of building and using PL/Java on Java 23.
The JDK 23 release notes do not announce any new features that would need to be exposed in PL/Java's API for use by user code.
Naturally, no patch will begin using Java 23 features within PL/Java _itself_ until a future major release adopts a newer minimum build version.
> Changes to build/use PL/Java on Java 23

- src/site/markdown/build/build.md
Issues #375 and #385 were closed as, essentially, pilot error (running Maven on a different version of Java than intended), but it would probably help to document that `mvn --version` does report the Java version Maven is using, so that can be easily checked.
> Document how to confirm Maven uses the right Java

- CI/integration
- pljava-api/src/main/java/org/postgresql/pljava/Session.java
- pljava-api/src/main/java/org/postgresql/pljava/SessionManager.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/JDBC42_21.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Modules.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/PassXML.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/SPIActions.java
- pljava-so/src/main/c/Backend.c
- pljava-so/src/main/c/SQLChunkIOOrder.c
- pljava-so/src/main/include/pljava/pljava.h
- pljava/src/main/java/org/postgresql/pljava/elog/ELogFormatter.java
- pljava/src/main/java/org/postgresql/pljava/internal/Backend.java
- pljava/src/main/java/org/postgresql/pljava/internal/Function.java
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pljava/src/main/java/org/postgresql/pljava/internal/Session.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLChunkIOOrder.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLInputFromChunk.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLOutputToChunk.java
- pljava/src/main/java/org/postgresql/pljava/nopolicy/FrozenProperties.java
- pljava/src/main/java/org/postgresql/pljava/nopolicy/package-info.java
- src/site/markdown/install/install.md.vm
- src/site/markdown/install/locatejvm.md
- src/site/markdown/install/smproperty.md
- src/site/markdown/install/vmoptions.md
- src/site/markdown/use/jpms.md
- src/site/markdown/use/policy.md
- src/site/markdown/use/unenforced.md
- src/site/markdown/use/use.md
- src/site/markdown/use/variables.md
Java 24, with [JEP 486][jep486], completes the process, begun with [JEP 411][jep411], of completely gutting Java's ability to enforce security policy, heavily relied on by PL/Java.
With this PR, PL/Java can still be used with all of its familiar policy-enforcement features, as long as `pljava.libjvm_location` points to a Java 23 or earlier JVM, and can also be used—with explicit variable settings to deliberately opt in—with no policy enforcement at all. Only this 'unenforced' mode is available when `pljava.libjvm_location` points to a Java 24 or later JVM.
This, at least, gives a DBA a choice. If a 'trusted' PL with policy enforcement is more important than the very latest Java language features, continue to use PL/Java with a Java 23 or earlier JVM, such as the long-term-support Java 21 …
> Allow use (with deliberate opt-in) with no security policy enforcement, as on Java >= 24

- src/site/markdown/develop/node.md
- src/site/markdown/index.md
- src/site/markdown/releasenotes-pre1_6.md.vm
- src/site/markdown/releasenotes.md.vm
- src/site/markdown/use/hello.md.vm
- src/site/markdown/use/jpms.md
- src/site/markdown/use/unenforced.md
- src/site/markdown/use/use.md
While PL/Java's docs are meant to build (`mvn site site:stage`) without failure on any Java version supported for building PL/Java, there have been changes over the Javadoc versions to things like the output directory structure and the spelling of anchor names for use as URL fragment IDs. Therefore, it's necessary to pick a version of Javadoc to be used when generating the docs if such things as links from the Markdown documents into the generated javadocs are to work right.
Links from the generated javadocs to Oracle's published JDK javadocs are made to the Java 12 pages as a practical compromise: PL/Java 1.6.x is built for compatibility back to Java 9, but Oracle's published pages for Java 12 are the earliest to have the organization expected for a modern Javadoc tool to link into them. …
> Assume javadoc-21 form for URLs linking into the javadocs

- .github/workflows/ci-lazypg.yml
- CI/integration
Starts were made back in 2020 on Windows tests in the GitHub Actions workflows, but they were not completed. Appveyor continued to be used for Windows CI, but at the cost of less parallelism among the matrix of tests and therefore slower results.
With this PR, the GitHub Actions workflow is now covering Linux (x64), Windows (x64, using MSVC or MinGW-w64), and Mac OS (x64 and arm64).
> Implement Windows MSVC and MinGW-w64 tests in GitHub Actions CI

- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/Loader.java
Have `withJarInPath` impose a temporary class path on a schema other than `public` only after also checking the `public` class path and not finding the jar there either. Addresses #516.
Also recast an ok but odd-looking `catch` block as a less-puzzling `finally`.
> Check public schema path too in withJarInPath

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/ConditionalDDR.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/saxon/S9.java
The Maven build has long offered an optional `-Psaxon-examples` profile; without it, the examples jar gets built without the `S9` example, and can be deployed in a database without the Saxon jar loaded. With the profile active, the jar is built with the `S9` example included, and then that jar can't be loaded (with `deploy => true`) unless the database already has a Saxon jar installed and on the class path, even if there is no need for the `S9` examples. That's an inconvenient restriction on later use of the examples jar based on a choice made at build time.
Use conditional execution in the deployment descriptor so that even when the examples jar is built with the `S9` examples included, they are only deployed if a Saxon API class is found on the class path at deploy time. That way, the …
> Declare `S9` example functions only if `s9api` on deploy-time class path

- pljava-api/src/main/java/org/postgresql/pljava/annotation/processing/DDRProcessor.java
- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/UDTScalarIOTest.java
- pljava/src/main/java/org/postgresql/pljava/internal/Backend.java
- pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLInputFromChunk.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
- pljava/src/main/java/org/postgresql/pljava/management/Commands.java
- pljava/src/main/java/org/postgresql/pljava/sqlj/Loader.java
These changes (plus, importantly, PR #512) take care of building and using PL/Java on Java 24.
The JDK 24 release notes do not announce any new features that would need to be exposed in PL/Java's API for use by user code.
Naturally, no patch will begin using Java 24 features within PL/Java itself until a future major release adopts a newer minimum build version.
> Other changes to build/use PL/Java on Java 24

- src/site/markdown/use/use.md
As #508 highlighted, information on the `log_min_messages` or `client_min_messages` settings needed for Java stack traces to be shown has been mentioned in passing in too many places for too many years while not described in the actual user documentation. Fix that.
The same new section is a reasonable place to also discuss how to attach a Java debugger.
> Document Java stack traces and debugger control

- pljava-so/src/main/c/VarlenaWrapper.c
When `VarlenaWrapper` wants to save a TOASTed value that may possibly be wanted later, it can use the least memory if it just retains the TOAST pointer and registers a current snapshot in which it is visible. In PG 9.6, a `GetOldestSnapshot` function appeared and made that possible. As of PG 18, with postgres/postgres@4d82750, that function has vanished, but there is a new one, `get_toast_snapshot`, that appears to fit the bill. It's only declared in `access/toast_internals.h`, though, which isn't otherwise needed.
Addresses #524.
> Changes needed for PG 18

- pljava-so/src/main/c/DualState.c
- pljava-so/src/main/c/ExecutionPlan.c
- pljava-so/src/main/c/Function.c
- pljava-so/src/main/c/HashMap.c
- pljava-so/src/main/c/SQLInputFromTuple.c
- pljava-so/src/main/c/SQLOutputToChunk.c
- pljava-so/src/main/c/SQLOutputToTuple.c
- pljava-so/src/main/c/VarlenaWrapper.c
- pljava-so/src/main/c/type/Composite.c
- pljava-so/src/main/c/type/ErrorData.c
- pljava-so/src/main/c/type/Portal.c
- pljava-so/src/main/c/type/Relation.c
- pljava-so/src/main/c/type/SingleRowReader.c
- pljava-so/src/main/c/type/TriggerData.c
- pljava-so/src/main/c/type/Tuple.c
- pljava-so/src/main/c/type/TupleDesc.c
- pljava-so/src/main/include/pljava/pljava.h
PostgreSQL itself has been requiring a C compiler that has `uintptr_t` since 9.0 (postgres/postgres@85d02a6). The PL/Java 1.6.x branch only supports back to PG 9.5, so there is no question the type is supported.
An existing static assert in `DualState.c` is hereby changed to assert that `sizeof(uintptr_t) <= sizeof(jlong)`; this is also assured for the present by a comment upstream in `postgres.h` section 1: "we require: sizeof(Datum) == sizeof(void *) == 4 or 8" (where `Datum` is `uintptr_t`).
In passing, specifically type as `SPIPlanPtr` some variables that had been typed `void *`. That was once their actual type in the SPI docs, but not since PG 8.2.
The few sites that ended up as `PointerGetDatum(JLongGet(Pointer,...))` are effectively a longwinded way of doing nothing, but I left …
> Streamline anachronistic `Ptr2Long` union usage

- pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/MishandledExceptions.java
- pljava-so/src/main/c/Exception.c
- pljava-so/src/main/c/Invocation.c
- pljava-so/src/main/c/JNICalls.c
- pljava-so/src/main/include/pljava/Exception.h
- pljava-so/src/main/include/pljava/JNICalls.h
- pljava/src/main/java/org/postgresql/pljava/internal/ServerException.java
- pljava/src/main/java/org/postgresql/pljava/internal/UnhandledPGException.java
- pljava/src/main/java/org/postgresql/pljava/jdbc/Invocation.java
- src/site/markdown/use/catch.md
- src/site/markdown/use/use.md
A not-uncommon mistake by newcomers to PL/Java is to catch an exception raised during a call back into PostgreSQL (such as through the internal JDBC interface), but then to try to proceed without either rolling back to a previously-established Savepoint or (re-)throwing the same or another exception. That leaves the PostgreSQL transaction in an undefined state, and PL/Java will reject subsequent attempts by Java code to call into PostgreSQL again. Those later rejections raise exceptions that may have no discernible connection to the original exception that was mishandled, and may come from completely unexpected places (a ClassNotFoundException from PL/Java's class loader, for example). Meanwhile, the actual exception that was originally mishandled to cause the problem may never be logged …
> Be more informative about mishandled exceptions
