pljava-so/src/main/c/type/AclId.c
As caught by mc-soi in #48.
Also eliminate some pre-8.1 conditional code.
Closes #48.
=> Use 2-arg GetUserNameFromId on PG 9.5+.

pljava-so/src/main/c/type/String.c
Exceptions thrown trying to load the first PL/Java implementation class
may need to be handled before String_init has completed, so String needs
some partial functionality at that point.
Was buried in installhelp branch a long time, but worth factoring out
while rebasing that branch for publication.
Closes #61.
=> Avoid crash on exception before String_init.

pljava-deploy/src/main/java/org/postgresql/pljava/deploy/Deployer.java, pljava-examples/src/main/java/org/postgresql/pljava/example/Triggers.java, pljava/src/main/java/org/postgresql/pljava/internal/Oid.java, pljava/src/main/java/org/postgresql/pljava/internal/Relation.java, pljava/src/main/java/org/postgresql/pljava/internal/TriggerData.java, pljava/src/main/java/org/postgresql/pljava/jdbc/SPIDatabaseMetaData.java, pljava/src/main/java/org/postgresql/pljava/management/Commands.java
Also factored out from the rebasing of installhelp.
=> More groveling before JDK 8's javadoc strictness.

pljava-so/src/main/c/type/Type.c
Discovered in code review without any reported issue, but confirmed in testing that it's possible to declare functions involving (what the new API calls) `ARRAYCOERCE` or `COERCEVIAIO` handling, and get crashes or Krueger numbers in builds without this patch. Now they throw 'not implemented' errors.
There is no reason those cases should not be implemented; the wiki language in "Function mapping" that says "a standard PostgreSQL explicit cast" will be performed would lead readers to expect those cases are implemented. In this patch, left for future work.
=> Track PG8.3 change to find_coercion_pathway API.

pljava-so/src/main/c/Session.c
Use, where present, the newer API introduced in PostgreSQL 9.0,
8.4.2, 8.3.9, and 8.2.15, eventually allowing removal of the
old API described in code comments as "only provided for ...
pljava" for a while now, and more recently requested by Noah Misch.
=> Track newer PG get/set user API.

pljava/src/main/java/org/postgresql/pljava/internal/Backend.java, pljava/src/main/java/org/postgresql/pljava/jdbc/Invocation.java, pljava/src/main/java/org/postgresql/pljava/sqlj/Loader.java
Pull request #89 was aimed at getting the PL/Java-loaded-versions announcement to be the only chatter at DEBUG1, but these sites were missed.
=> Keep making DEBUG1 quieter.

pljava-api/src/main/java/org/postgresql/pljava/TriggerData.java, pljava-examples/src/main/java/org/postgresql/pljava/example/annotation/Triggers.java, pljava/src/main/java/org/postgresql/pljava/internal/TriggerData.java
Adds to TriggerData the suppress() method suggested in issue #142.
=> Enable row triggers to suppress operations.

pljava-api/src/main/java/org/postgresql/pljava/sqlgen/DDRProcessor.java
This will make it easier to support idioms where a Java
parameter or return is typed A\<B> (or some C that directly or
indirectly extends A\<B>) and the generator needs to find B.
Fixes a latent (in this branch) bug where parameterized return
types could be written into the AS string in all their glory,
instead of properly as their erasures. It's latent in this branch
because the only use made of parameterized return types is for
SETOF with Iterator<T>, and the return type isn't written for that
case, but would become a real bug with any future addition of other
idioms involving parameterized return types.
First done in an explorative branch against master, with this
generally-useful refactoring rebased here. A couple other minor
differences from master are also included here, to keep …
=> Factor out 'specialization' check in SQL generator.

pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java, pljava/src/main/java/org/postgresql/pljava/jdbc/XMLEventToStreamConsumer.java, src/site/markdown/use/sqlxml.md
Best time to fix these is before they are reported from the field. See #272 for analysis.
=> Fix several bugs in SQLXML handling

pljava-examples/src/main/java/org/postgresql/pljava/example/saxon/S9.java
XML-typed output columns didn't work because of a simple omitted test for the type.
XML-typed input parameters didn't work because of the (extension to the spec) choice to make them available to column expressions as well as to the row expression, while the JDBC `SQLXML` type is only allowed to be read one time. It doesn't make sense to do the work of tree building more than once anyway, so simply cache the built tree rather than the `SQLXML` object.
Addresses #280.
=> Fix XMLTABLE for XML-typed columns and named parameters

appveyor.yml
Otherwise, AppVeyor (for which "the minimal appveyor.yml file is an empty file" and "all sections are optional") will feel that it should be doing something, and report that nothing succeeded.
I would hold the more optimistic view and say that nothing failed.
=> Add a do-nothing appveyor.yml where nothing to do

pljava-so/src/main/c/PgSavepoint.c
EnterpriseDB added a `ReleaseCurrentSubTransactionEx` function with an added argument, and made `ReleaseCurrentSubTransaction` call it, passing `false`. But instead of leaving `ReleaseCurrentSubTransaction` an actual function that does so, which would not have been an API break, they made it a macro instead, with the result that its address cannot be taken.
I would have preferred to condition this workaround on specific affected EDB versions, if the reporter of the issue had been able to get such specifics from EDB, but no such response was forthcoming. So this workaround is just conditioned on finding `ReleaseCurrentSubTransaction` defined as a macro.
=> Workaround #260, PostgreSQL API breakage by EnterpriseDB

pom.xml
Play another round of the "Maven stopped building the docs correctly, make it start again" game.
=> Make Markdown rendering work, again

pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java
Instead of looking for an element name inside some kind of punctuation, just ~~use negative lookahead/lookbehind to match the expected element name neither preceded nor followed by another XML `NameChar`~~ match the expected element only when we know it will appear, and only once (the expected occurrence will definitely be the first).
Addresses #312.
Worthy of backpatching to 1.5, ~~but might have to be done in simplified form without using~~ and in rethought form does not require the newer regexp syntax.
=> Mistrust localized punctuation (issue #312)

pljava-examples/src/main/java/org/postgresql/pljava/example/saxon/S9.java
Though the normal build is without -Xlint, the unchecked warning summary message was showing up in CI build logs.
=> Fix some lint warnings in the S9 example

pljava-so/src/main/c/TypeOid.c, pljava-so/src/main/c/VarlenaWrapper.c, pljava-so/src/main/c/type/ErrorData.c, pljava-so/src/main/c/type/SQLXMLImpl.c, pljava-so/src/main/include/pljava/pljava.h, pljava/src/main/java/org/postgresql/pljava/internal/ErrorData.java, pljava/src/main/java/org/postgresql/pljava/jdbc/SQLXMLImpl.java, pljava/src/main/java/org/postgresql/pljava/jdbc/TypeOid.java
The needed changes seem fairly minor this time.
=> Support building against PostgreSQL 14

pljava-so/src/main/c/Backend.c
A thinko in the validator handler sought to avoid one problem by inviting another; if the validator handler is called before initialization is complete, its preemptive early setting of `pljavaLoadPath` could be interpreted in the `initsequencer` as indicating an explicit `LOAD` or `CREATE EXTENSION`, calling for the `sqlj` schema to be populated or migrated. During a `pg_upgrade`, that schema might not yet be fully populated, foiling the schema recognition/migration code.
So, rather than preemptively setting the load path, just avoid the exact problem the code was meant to avoid, in a more direct manner.
Addresses #352.
=> Trigger no sqlj schema groundwork from validator

pljava-api/src/main/java/org/postgresql/pljava/sqlgen/Lexicals.java, pljava-api/src/test/java/LexicalsTest.java
I don't have any PL/Java application in mind that would involve serializing identifiers (or `Principal`s containing them), but the `Subject` class requires `Principal`s that are serializable, and if the code has to be there, it shouldn't be untested/buggy.
=> Tighten deserialization of Identifier

pljava-so/src/main/c/Backend.c
`WARNING` may be needlessly alarming for a notice about an issue that's expected to become a problem in "some Java version after 17 (LTS)." The level was chosen so as not to be silenced by the reporting level set within `CREATE EXTENSION`. But then it was moved to be emitted only at successful transaction end, so as not to clutter any actual error messages, and that in itself solves the suppressed-by-`CREATE EXTENSION` issue, so it is possible to use the less-alarming `NOTICE` level when running on Java versions after 11 but before 17.
=> Downgrade JEP411 WARNING to NOTICE on < 17

pljava-api/src/main/java/org/postgresql/pljava/annotation/BaseUDT.java
These changes should have been included in pull request #256, but were overlooked at the time.
=> Update obsolete javadoc information

pljava/src/main/java/org/postgresql/pljava/internal/Function.java
The `TRANSFORM FOR TYPE` mechanism is only meaningful for a PL whose handler function itself does the work of looking up and applying the transforms.
https://www.postgresql.org/message-id/61FDBCFE.3090800%40anastigmatix.net
This PL doesn't, so say so when validating a function declaration that includes a `TRANSFORM` clause. Addresses #402.
It would arguably be better to say so even earlier, at an attempted `CREATE TRANSFORM` for the PL, but PostgreSQL does not currently apply any PL-specific validator function at that time. An event trigger could be used, but that would be far too much fuss just to provide a better message in an event so unlikely to occur.
=> Fail validation if TRANSFORM FOR TYPE declared

pljava-so/src/main/c/type/String.c
Addresses #416, an unlikely scenario that combined a database set for `SQL_ASCII` with an unworkable setting in `pljava.vmoptions`, where the combination caused an `UnsupportedCharsetException` during initialization in `String.c`, and `elogExceptionMessage` tried to use the incompletely-initialized `String` routines, causing a crash.
Effort had been put in `String.c` to avoid such outcomes, by having initial values of `uninitialized` and `s_two_step_conversion` that provide a fallback capability before initialization is complete. However, the initial value of `s_two_step_conversion` could be changed to its runtime-determined value too early, with some other initialization steps yet to be done.
=> Avoid crash on exception in String initialization
